### ISSUE TITLE
Can not use str.GetJsonFromUrl() with URL Encoded chars nor special chars (ÅÄÖ)

### ISSUE THREAD

**Issue by danielHalan** [ServiceStack/Issues#225]
When trying to call a URL using GetJsonFromUrl() that contains special characters the following exception is thrown, 
Both when sending Url non-urlencoded, and .UrlEncode():ed

Test URLs
"http://maps.google.com/maps/api/geocode/json?address=Brännkyrkagatan 56"
"http://maps.google.com/maps/api/geocode/json?address=Br%c3%a4nnkyrkagatan%252056"

```
   at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
   at System.Security.Permissions.FileIOPermission.CheckIllegalCharacters(String[] str)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, AccessControlActions control, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission.AddPathList(FileIOPermissionAccess access, String[] pathListOrig, Boolean checkForDuplicates, Boolean needFullPath, Boolean copyPathList)
   at System.Security.Permissions.FileIOPermission..ctor(FileIOPermissionAccess access, String path)
   at System.Configuration.UriSectionReader.GetSectionData()
   at System.Configuration.UriSectionReader.Read(String configFilePath, UriSectionData parentData)
   at System.Configuration.UriSectionInternal.LoadUsingCustomParser(String appConfigFilePath)
   at System.Configuration.UriSectionInternal.GetSection()
   at System.Uri.InitializeUriConfig()
   at System.Uri.InitializeUri(ParsingError err, UriKind uriKind, UriFormatException& e)
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString)
   at System.Net.WebRequest.Create(String requestUriString)
   at ServiceStack.HttpUtils.SendStringToUrl(String url, String method, String requestBody, String contentType, String accept, Action`1 requestFilter, Action`1 responseFilter)
   at ServiceStack.HttpUtils.GetStringFromUrl(String url, String accept, Action`1 requestFilter, Action`1 responseFilter)
   at ServiceStack.HttpUtils.GetJsonFromUrl(String url, Action`1 requestFilter, Action`1 responseFilter)
   at Itq.Legal.Services.Geo.GeoLocationService.ResolveLocation(String[] street, String city, String zipCode, String countryISO2) in c:\Halan\ITQ\02.Projects\Legal\03.Development\System\Itq.Legal.Services.Geo\GeoLocationService.cs:line 22
   at Itq.Legal.Services.Tests.when_resolving_street_address_to_geo_location.<.ctor>b__1() in c:\Halan\ITQ\02.Projects\Legal\03.Development\System\Itq.Legal.Services.Tests\GetLocationTests.cs:line 28
```

**Comment by mythz** [comment]
Just tried this and it does work:

```csharp
var url = "http://maps.google.com/maps/api/geocode/json?address=Brännkyrkagatan 56";
url.GetJsonFromUrl().Print();
```

It prints out:

```
{
   "results" : [
      {
         "address_components" : [
            {
               "long_name" : "56",
               "short_name" : "56",
               "types" : [ "street_number" ]
            },
            {
               "long_name" : "Brännkyrkagatan",
               "short_name" : "Brännkyrkagatan",
               "types" : [ "route" ]
            },
            {
               "long_name" : "Södermalm",
               "short_name" : "Södermalm",
               "types" : [ "sublocality_level_1", "sublocality", "political" ]
            },
            {
               "long_name" : "Stockholm",
               "short_name" : "Stockholm",
               "types" : [ "locality", "political" ]
            },
            {
               "long_name" : "Stockholm",
               "short_name" : "Stockholm",
               "types" : [ "postal_town" ]
            },
            {
               "long_name" : "Stockholms län",
               "short_name" : "Stockholms län",
               "types" : [ "administrative_area_level_1", "political" ]
            },
            {
               "long_name" : "Sweden",
               "short_name" : "SE",
               "types" : [ "country", "political" ]
            },
            {
               "long_name" : "11822",
               "short_name" : "11822",
               "types" : [ "postal_code" ]
            }
         ],
         "formatted_address" : "Brännkyrkagatan 56, 118 22 Stockholm, Sweden",
         "geometry" : {
            "location" : {
               "lat" : 59.3189794,
               "lng" : 18.0576462
            },
            "location_type" : "ROOFTOP",
            "viewport" : {
               "northeast" : {
                  "lat" : 59.32032838029151,
                  "lng" : 18.0589951802915
               },
               "southwest" : {
                  "lat" : 59.31763041970849,
                  "lng" : 18.0562972197085
               }
            }
         },
         "types" : [ "street_address" ]
      }
   ],
   "status" : "OK"
}
```

**Comment by danielHalan** [comment]
Some issue with MSpec VStudio Test instance, when added following to TestProjects app.config it now works.
```
  <uri>
  <idn enabled="All" />
  <iriParsing enabled="true" />
  </uri>
```

**Comment by mythz** [comment]
ok cool, good to know, thx.
