### ISSUE TITLE
SSE throw licensing exception

### ISSUE THREAD

**Issue by Nness** [ServiceStack/Issues#232]
Here is stacktrace for this issue:

"ServiceStack.LicenseException: The free-quota limit on '20 ServiceStack.Text Types' has been reached. Please see https://servicestack.net to upgrade to a commercial license or visit https://github.com/ServiceStackV3/ServiceStackV3 to revert back to the free ServiceStack v3.
   at ServiceStack.LicenseUtils.ApprovedUsage(LicenseFeature licenseFeature, LicenseFeature requestedFeature, Int32 allowedUsage, Int32 actualUsage, String message)
   at ServiceStack.LicenseUtils.AssertValidUsage(LicenseFeature feature, QuotaType quotaType, Int32 count)
   at ServiceStack.Text.TypeConfig.AssertValidUsage()
   at ServiceStack.Text.TypeConfig`1.AssertValidUsage()
   at ServiceStack.Text.Json.JsonReader`1.Parse(String value)
   at ServiceStack.Text.JsonSerializer.DeserializeFromString[T](String value)
   at ServiceStack.Text.JsonObject.Parse(String json)
   at ServiceStack.ServerEventsClient.ProcessOnConnectMessage(ServerEventMessage e)
   at ServiceStack.ServerEventsClient.ProcessEventMessage(ServerEventMessage e)
   at ServiceStack.ServerEventsClient.<>c__DisplayClass5.<ProcessResponse>b__4(Task`1 t)
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()"

SSE Client disconnect right after onConnect object received. Client version 4.0.36.0

**Comment by mythz** [comment]
ok should now be resolved with the latest v4.0.37+ that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by Nness** [comment]
Cool thx.
