### ISSUE TITLE
JSConfig.Reset() Argument Null Exception

### ISSUE THREAD

**Issue by laurencee** [ServiceStack/Issues#244]
I'm using ServiceStack in a CLR Trigger (from inserts, updates and deletes) to do some datetime conversions and occasionally I'll run across this error which requires me to restart the app domain to fix the problem.

The exception thrown from JSConfig.Reset():
```
"System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentNullException: Value cannot be null.
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at ServiceStack.Text.JsConfig.Reset(Type cachesForType)
   at ServiceStack.Text.JsConfig.Reset()
   at Helper.SetISODatetime()"
```
(Note this could also occur from the SetLocalDateTime() call as well since they both do JSConfig.Reset())

The CLR trigger is loaded as such:
```sql
CREATE TRIGGER [dbo].[clrtrig_Calendar] ON [dbo].[Calendar] 
WITH EXECUTE AS CALLER AFTER  INSERT, DELETE, UPDATE AS 
EXTERNAL NAME [ClrTriggers].[CalendarTrigger]
GO
```

This happens for both SQL Server 2012 and 2014 express (x64) and occurs from the following:
I've only seen the exception occur when running load tests such inserts/updates/deletes in a loop for an extended period of time:

```sql
  DECLARE @CalDate smalldatetime
  SET @CalDate = '2015-01-01'

INSERT INTO [dbo].[Calendar] VALUES (@CalDate,1,0,0,1)
update [dbo].[Calendar] SET notopen = 0 where CalDate = @CalDate
delete from [dbo].[Calendar] where CalDate = @CalDate
```

When the CLR trigger fires depending on the table I set a different datetime serialization function. 

```c#
        public static void SetISODatetime()
        {
            JsConfig.Reset();
            JsConfig<DateTime>.SerializeFn = time => time.ToString("O");

            JsConfig<DateTime?>.SerializeFn =
                time =>
                {
                    if (time == null) return null;
                    return time.Value.ToString("O");
                };
        }

        public static void SetLocalDateTime()
        {
            JsConfig.Reset();
            JsConfig<DateTime>.SerializeFn =
                time =>
                    TimeZoneInfo.ConvertTime(time, QldTimezone, TimeZoneInfo.Local)
                        .ToString(DateTimeSerializer.DateTimeFormatSecondsUtcOffset);

            JsConfig<DateTime?>.SerializeFn =
                time =>
                {
                    if (time == null) return null;
                    return TimeZoneInfo.ConvertTime(time.Value, QldTimezone, TimeZoneInfo.Local)
                        .ToString(DateTimeSerializer.DateTimeFormatSecondsUtcOffset);
                };
        }
```

**Comment by mythz** [comment]
Why do you need to call `JsConfig.Reset()`?

**Comment by mythz** [comment]
The `JsConfig` is for setting static configuration, the `Reset()` is really just a helper to invalidate some caches for unit testing. Instead of overriding the serialization handler multiple times at runtime can you just register the handler once and use a configuration option to alternate between the different methods, e.g:

```csharp
public static class Config {
    public static bool UseISO = true;

    public static void Init() {
        JsConfig<DateTime>.SerializeFn = 
            time => Config.UseISO 
                ? time.ToString("O")
                : TimeZoneInfo.ConvertTime(time, QldTimezone, TimeZoneInfo.Local)
                    .ToString(DateTimeSerializer.DateTimeFormatSecondsUtcOffset);
    }
}

public static void SetISODatetime()
{
    Config.UseISO = true;
}

public static void SetLocalDateTime()
{
    Config.UseISO = false;
}
```

**Comment by laurencee** [comment]
That's a good idea. :+1: 
Thanks for the suggestion, I'll go with that configuration variable approach instead.

Sometimes get caught up with how things work right now and lose perspective.

**Comment by mythz** [comment]
Great sounds like a plan :)
