### ISSUE TITLE
Asp.Net await on SS client async method cause task exception.

### ISSUE THREAD

**Issue by Nness** [ServiceStack/Issues#247]
Server application is .Net 4.5.2 with webapi 4.0.20710.0 (webapi - 1), Servicestack 4.0.38

SS client async method sometime never ends and with task unobserved exception logged.

Handle,Task Unobserved Task Exception,"System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Web.ThreadContext.AssociateWithCurrentThread(Boolean setImpersonationContext)
   at System.Web.HttpApplication.OnThreadEnterPrivate(Boolean setImpersonationContext)
   at System.Web.HttpApplication.System.Web.Util.ISyncContext.Enter()
   at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
   at System.Threading.Tasks.Task.Execute()"

Example of code:

async Task<HttpResponseMessage> Example() {
    var res = await gateway.ActionAsync();
}

async Task<object> Gateway.ActionAsync() {
    var dbobj = await ravenDbSession.GetDocument().ConfigureAwait(false);
    Log.Info("SS start post async");
    var result = await _jsonServiceClient.PostAsync(dto).ConfigureAwait(false);
    Log.Info("SS end post async");
    return result;
}

This service will not always fail, but once fail, you can see "SS start post async" within log but not end post message. Also with Task unobserved Task Exception.

Task unobserved Task Exception sometime not report immediately but after period of time. From fiddler you can see those service call never ends.

I have tried to change code to var result = await _jsonServiceClient.PostAsync(dto); without success.

Once I change to var result = _jsonServiceClient.Post(dto). It runs fine without issue.

Same exception been reported on servicestack: http://stackoverflow.com/questions/28834471/nullreferenceexception-when-using-event-with-timeout

From what they are saying is Asp.Net issue, But webApi's HttpClient never had issue, maybe because they never had timeout setting? (RavenDB underlying was using HttpClient).

Just curious if you have any clue on this issue.

**Comment by mythz** [comment]
Do you have a stand-alone repro of this issue? i.e. something that can be run locally that repro's this issue?

**Comment by Nness** [comment]
I will try to create a reproduce.

On top of that, I just spot another issue that's similar to this. 

Exception: 
CreateErrorResponse,ServiceBase<TRequest>::Service Exception,"System.InvalidOperationException: An attempt was made to transition a task to a final state when it had already completed.
   at System.Threading.Tasks.TaskCompletionSource`1.SetResult(TResult result)
   at ServiceStack.EventSubscription.Dispose()
   at ServiceStack.MemoryServerEvents.HandleUnsubscription(IEventSubscription subscription)
   at ServiceStack.MemoryServerEvents.Notify(ConcurrentDictionary`2 map, String key, String selector, Object message, String channel)
   at ServiceStack.MemoryServerEvents.NotifyChannel(String channel, String selector, Object message)
   at DeskDirector.Messaging.ServiceInterface.ServerEventExtension.NotifyToChannels(IServerEvents events, String[] channels, String selector, Object message) in c:\Projects\DeskDirector\DeskDirector 2014\DeskDirector.Messaging\DeskDirector.Messaging.ServiceInterface\ServerEventExtension.cs:line 133
   at DeskDirector.Messaging.ServiceInterface.ChatServices.<Post>d__14.MoveNext() in c:\Projects\DeskDirector\DeskDirector 2014\DeskDirector.Messaging\DeskDirector.Messaging.ServiceInterface\ChatServices.cs:line 137"


From code, I call several notify channel, then execute a "await" method without configureawait(false). It throw up that exception. There is no "await" action before notify to channels.

**Comment by Nness** [comment]
mythz:

I have tried to create a project to reproduce this issue, but failed to do so. I couldn't figure out the difference between original and the one I made.

I will use sync method for now, once I can reproduce it I will let you know. 

Thanks
