### ISSUE TITLE
Registering your License Key with your ServiceStack Projects

### ISSUE THREAD

**Issue by andreimatusevich** [ServiceStack/Issues#298]
I am having issue using option a) Add it to your Web.Config (option b works)

We are running self-hosted web service 
I tried both
``` 
    <appSettings>
        <!-- Please ensure that you set same ServiceName in app.config and ServiceInstaller -->
        <add key="servicestack:license" value="{key}" />
        <add key="ServiceName" value="UploaderRestService" />

    <appSettings>
        <!-- Please ensure that you set same ServiceName in app.config and ServiceInstaller -->
        <add key="servicestack:license" value="key" />
        <add key="ServiceName" value="UploaderRestService" />
```
And I am getting the following error: The ServiceName setting had an invalid format. The value "UploaderRestService" could not be cast to type System.String

Details:
``` 
System.Configuration.ConfigurationErrorsException was unhandled
  HResult=-2146232062
  Message=The ServiceName setting had an invalid format. The value "UploaderRestService" could not be cast to type System.String
  Source=ServiceStack
  BareMessage=The ServiceName setting had an invalid format. The value "UploaderRestService" could not be cast to type System.String
  Line=0
  StackTrace:
       at ServiceStack.Configuration.AppSettingsBase.Get[T](String name, T defaultValue)
       at Imagine.Service.Common.AppListenerHost.GetServiceName() in c:\code\devel_fixes\ManagementConsole\Imagine.Service.Common\SelfHostedServiceBase.cs:line 194
       at Imagine.Service.Common.AppListenerHost..ctor(Assembly[] assembliesWithServices) in c:\code\devel_fixes\ManagementConsole\Imagine.Service.Common\SelfHostedServiceBase.cs:line 178
       at Imagine.Uploader.Service.UploaderHost..ctor() in c:\code\devel_fixes\ManagementConsole\Imagine.Uploader.Service\UploaderHost.cs:line 41
       at Imagine.Uploader.Service.Program.Main(String[] args) in c:\code\devel_fixes\ManagementConsole\Imagine.Uploader.Service\Program.cs:line 22
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: System.TypeInitializationException
       HResult=-2146233036
       Message=The type initializer for 'ServiceStack.Text.Jsv.JsvReader`1' threw an exception.
       Source=ServiceStack.Text
       TypeName=ServiceStack.Text.Jsv.JsvReader`1
       StackTrace:
            at ServiceStack.Text.Jsv.JsvReader`1.Parse(String value)
            at ServiceStack.Text.TypeSerializer.DeserializeFromString[T](String value)
            at ServiceStack.Configuration.AppSettingsBase.Get[T](String name, T defaultValue)
       InnerException: System.TypeInitializationException
            HResult=-2146233036
            Message=The type initializer for 'ServiceStack.Text.Common.JsReader`1' threw an exception.
            Source=ServiceStack.Text
            TypeName=ServiceStack.Text.Common.JsReader`1
            StackTrace:
                 at ServiceStack.Text.Common.JsReader`1.GetCoreParseFn[T]()
                 at ServiceStack.Text.Common.JsReader`1.GetParseFn[T]()
                 at ServiceStack.Text.Jsv.JsvReader`1..cctor()
            InnerException: System.TypeInitializationException
                 HResult=-2146233036
                 Message=The type initializer for 'ServiceStack.Text.Common.JsWriter' threw an exception.
                 Source=ServiceStack.Text
                 TypeName=ServiceStack.Text.Common.JsWriter
                 StackTrace:
                      at ServiceStack.Text.Common.JsWriter.GetTypeSerializer[TSerializer]()
                      at ServiceStack.Text.Common.JsReader`1..cctor()
                 InnerException: System.TypeInitializationException
                      HResult=-2146233036
                      Message=The type initializer for 'ServiceStack.Text.JsConfig' threw an exception.
                      Source=ServiceStack.Text
                      TypeName=ServiceStack.Text.JsConfig
                      StackTrace:
                           at ServiceStack.Text.JsConfig.get_EmitCamelCaseNames()
                           at ServiceStack.Text.Common.JsWriter..cctor()
                      InnerException: System.TypeInitializationException
                           HResult=-2146233036
                           Message=The type initializer for 'ServiceStack.LicenseUtils' threw an exception.
                           Source=ServiceStack.Text
                           TypeName=ServiceStack.LicenseUtils
                           StackTrace:
                                at ServiceStack.LicenseUtils.Init()
                                at ServiceStack.Text.JsConfig..cctor()
                           InnerException: ServiceStack.LicenseException
                                HResult=-2146233088
                                Message=This license is invalid. Please see servicestack.net or contact team@servicestack.net for more details. The id for this license is '2627'
                                Source=ServiceStack.Text
                                StackTrace:
                                     at ServiceStack.LicenseUtils.RegisterLicense(String licenseKeyText)
                                     at ServiceStack.Net40PclExport.RegisterLicenseFromConfig()
                                     at ServiceStack.LicenseUtils..cctor()
                                InnerException:
```

**Comment by mythz** [comment]
This exception is being raised in custom application code, (i.e not in ServiceStack):

      at Imagine.Service.Common.AppListenerHost.GetServiceName() in c:\code\devel_fixes\ManagementConsole\Imagine.Service.Common\SelfHostedServiceBase.cs:line 194

**Comment by andreimatusevich** [comment]
Judging by inner exception property it was raised in ServiceStack.Text
```
InnerException: ServiceStack.LicenseException
                                HResult=-2146233088
                                Message=This license is invalid. Please see servicestack.net or contact team@servicestack.net for more details. The id for this license is '2627'
```
Just in case GetServiceName() function 
```
        public static string GetServiceName()
        {
            return AppSettings.Get("ServiceName", "Service");
        }
```
Licensing.RegisterLicense works for me. Probably as a workaround i can manually load license value from web.config. and RegisterLicense.

**Comment by mythz** [comment]
hmm, can you try with the [latest version on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet) to see if it resolves the issue?

**Comment by mythz** [comment]
Reopen Issue with more info or a repro in order to be able to investigate further.
