### ISSUE TITLE
Reflection.ReflectionTypeLoadException => Markdown eveluator 

### ISSUE THREAD

**Issue by stephenpatten** [ServiceStack/Issues#321]
Hello,

I'm receiving the error below from the latest MyGet packages (4.0.43) and in order to help you diagnose the issue, would you please add some extra logging on your side and inspect the "LoaderExceptions property" and dump the pertanant information out.

FYI:  There are no assemblies named  "LO.Leads.ServiceModel.Api.DirectApi", it's a namespace. 

Everything has gone downhill after adding support for buffering?

	PreRequestFilters.Add((httpReq, httpRes) =>
	{
		httpReq.UseBufferedStream = true;
		httpRes.UseBufferedStream = true;
	});

Can't load assembly: LO.Leads.ServiceModel.Api.DirectApi
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeModule.GetTypes()
   at System.Reflection.Assembly.GetTypes()
   at ServiceStack.Support.Markdown.Evaluator.<FindNamespaceInLoadedAssemblies>b__1(Assembly assembly)
   at System.Linq.Enumerable.<SelectManyIterator>d__31`3.MoveNext()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at ServiceStack.Support.Markdown.Evaluator.FindNamespaceInLoadedAssemblies(String assemblyNamespace)
   at ServiceStack.Support.Markdown.Evaluator.AddAssembly(String assemblyName)
 CallSite
ServiceStack.Support.Markdown.Evaluator.AddAssembly

 Logger => Evaluator

**Comment by mythz** [comment]
It's having trouble scanning assemblies paths, you prevent it scanning directories with `Config.ScanSkipPaths` or if you're not using it you can [remove Markdown Plugin](https://github.com/ServiceStack/Issues/issues/318#issuecomment-120451703) with:

    Plugins.RemoveAll(x => x is MarkdownFormat);

**Comment by stephenpatten** [comment]
Going with removing the plug-in, as the service it's trying to document works perfect.

**Comment by stephenpatten** [comment]
Verified fix.
