### ISSUE TITLE
ServiceStack crashes inside AzureWorker role (Object ref. not of an instance...)

### ISSUE THREAD

**Issue by danielHalan** [ServiceStack/Issues#332]
When running code that works perfectly fine in console, but inside a Azure Worker role SS License Utils crashes, Have done a small example, 

```
      public override bool OnStart() {
        try {
          ServiceStack.Licensing.RegisterLicense(ConfigurationManager.AppSettings["servicestack:license"]);
 
          return base.OnStart();
 
        } catch( Exception ex ) {
          _log.Error(ex.ToString());
 
          return false;
        }
      }
```

![image](https://cloud.githubusercontent.com/assets/641348/9054433/90d7f912-3aab-11e5-86d9-535dab2c622d.png)

**Comment by mythz** [comment]
Wasn't able to reproduce this in an Azure Web Job, what VS.NET Azure Template did you use to create the worker role?

**Comment by monchaio** [comment]
Hi @mythz I'm Monchai and I work under @danielHalan I would like to give you more information about our system. Our system run under Cloud worker role plus NServiceBus and below is full call stack that throw an error from our code when we try to run below command

    public T Deserialize<T>(System.IO.Stream input) {
      var obj = (T)ServiceStack.Text.JsonSerializer.DeserializeFromStream(typeof(T), input);

=== Call Stack ===
2015/08/06 09:19:04.263 Info Failed to process message System.TypeInitializationException: The type initializer for 'ServiceStack.Text.Json.JsonReader`1' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ServiceStack.Text.Common.DeserializeDictionary`1' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ServiceStack.Text.Common.JsWriter' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ServiceStack.Text.JsConfig' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ServiceStack.LicenseUtils' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceStack.LicenseUtils..cctor()
   --- End of inner exception stack trace ---
   at ServiceStack.LicenseUtils.Init()
   at ServiceStack.Text.JsConfig..cctor()
   --- End of inner exception stack trace ---
   at ServiceStack.Text.JsConfig.get_EmitCamelCaseNames()
   at ServiceStack.Text.Common.JsWriter..cctor()
   --- End of inner exception stack trace ---
   at ServiceStack.Text.Common.JsWriter.GetTypeSerializer[TSerializer]()
   at ServiceStack.Text.Common.DeserializeDictionary`1..cctor()
   --- End of inner exception stack trace ---
   at ServiceStack.Text.Common.DeserializeDictionary`1.GetParseMethod(Type type)
   at ServiceStack.Text.Common.JsReader`1.GetCoreParseFn[T]()
   at ServiceStack.Text.Common.JsReader`1.GetParseFn[T]()
   at ServiceStack.Text.Json.JsonReader`1.Refresh()
   at ServiceStack.Text.Json.JsonReader`1..cctor()
   --- End of inner exception stack trace ---
   at ServiceStack.Text.Json.JsonReader`1.GetParseFn()
   at ServiceStack.Text.Json.JsonReader.GetParseFn(Type type)
   at ServiceStack.Text.JsonSerializer.DeserializeFromString(String value, Type type)
   at ServiceStack.Text.JsonSerializer.DeserializeFromStream(Type type, Stream stream)
   at EventSerializer.Deserialize[T](Stream input) in c:\xxxxx\EventSerializer.cs:line 33
   at NEventStore.Serialization.SerializationExtensions.Deserialize[T](ISerialize serializer, Byte[] serialized) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\Serialization\SerializationExtensions.cs:line 42
   at NEventStore.Persistence.Sql.CommitExtensions.Deserialize[T](ISerialize serializer, IDataRecord record, Int32 index) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\Persistence\Sql\CommitExtensions.cs:line 69
   at NEventStore.Persistence.Sql.CommitExtensions.GetCommit(IDataRecord record, ISerialize serializer, ISqlDialect sqlDialect) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\Persistence\Sql\CommitExtensions.cs:line 26
   at NEventStore.Persistence.Sql.SqlPersistenceEngine.<>c__DisplayClass3.<GetFrom>b__2(IDataRecord x) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\Persistence\Sql\SqlPersistenceEngine.cs:line 109
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at NEventStore.Persistence.PipelineHooksAwarePersistanceDecorator.<ExecuteHooks>d__3.MoveNext() in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\Persistence\PipelineHooksAwarePersistanceDecorator.cs:line 137
   at NEventStore.OptimisticEventStream.PopulateStream(Int32 minRevision, Int32 maxRevision, IEnumerable`1 commits) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\OptimisticEventStream.cs:line 122
   at NEventStore.OptimisticEventStream..ctor(String bucketId, String streamId, ICommitEvents persistence, Int32 minRevision, Int32 maxRevision) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\OptimisticEventStream.cs:line 35
   at NEventStore.OptimisticEventStore.OpenStream(String bucketId, String streamId, Int32 minRevision, Int32 maxRevision) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\OptimisticEventStore.cs:line 75
   at NEventStore.StoreEventsExtensions.OpenStream(IStoreEvents storeEvents, String bucketId, Guid streamId, Int32 minRevision, Int32 maxRevision) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\StoreEventsExtensions.cs:line 95
   at CommonDomain.Persistence.EventStore.EventStoreRepository.OpenStream(String bucketId, Guid id, Int32 version, ISnapshot snapshot) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\CommonDomain\Persistence\EventStore\EventStoreRepository.cs:line 162
   at CommonDomain.Persistence.EventStore.EventStoreRepository.GetById[TAggregate](String bucketId, Guid id, Int32 versionToLoad) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\CommonDomain\Persistence\EventStore\EventStoreRepository.cs:line 55
   at CommonDomain.Persistence.EventStore.EventStoreRepository.GetById[TAggregate](String bucketId, Guid id) in c:\TeamCity\buildAgent\work\38b1777f2112a252\src\NEventStore\CommonDomain\Persistence\EventStore\EventStoreRepository.cs:line 49
   at EventStore.DomainContext.GetAggregate[T](Guid id, String tenant, Boolean gracious) in c:\xxxxx\DomainContext.cs:line 129
   at EventStore.DomainContext.GetAggregate[T](Guid id) in c:\xxxx\DomainContext.cs:line 149
   at CommandHandlers.Tenant.CaseCommandHandler.Handle(ChangeCaseName m) in c:\xxxxx\CaseCommandHandler.cs:line 116
   at lambda_method(Closure , Object , Object )
   at NServiceBus.Unicast.MessageHandlerRegistry.Invoke(Object handler, Object message, Dictionary`2 dictionary) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\MessageHandlerRegistry.cs:line 124
   at NServiceBus.Unicast.MessageHandlerRegistry.InvokeHandle(Object handler, Object message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\MessageHandlerRegistry.cs:line 85
   at NServiceBus.LoadHandlersBehavior.<Invoke>b__1(Object handlerInstance, Object message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\LoadHandlersBehavior.cs:line 40
   at NServiceBus.InvokeHandlersBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\InvokeHandlersBehavior.cs:line 23
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.SagaPersistenceBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Sagas\SagaPersistenceBehavior.cs:line 41
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at ServiceControl.Plugin.SagaAudit.CaptureSagaStateBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\f7bdf8147ca393ba\src\ServiceControl.Plugin.Nsb5.SagaAudit\CaptureSagaStateBehavior.cs:line 31
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.SetCurrentMessageBeingHandledBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\SetCurrentMessageBeingHandledBehavior.cs:line 17
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.LoadHandlersBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\LoadHandlersBehavior.cs:line 47
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.InvokeSagaNotFoundBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\InvokeSagaNotFoundBehavior.cs:line 19
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.ApplyIncomingMessageMutatorsBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageMutator\ApplyIncomingMessageMutatorsBehavior.cs:line 24
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.ExecuteLogicalMessagesBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Messages\ExecuteLogicalMessagesBehavior.cs:line 24
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.CallbackInvocationBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\CallbackInvocationBehavior.cs:line 23
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.DeserializeLogicalMessagesBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Messages\DeserializeLogicalMessagesBehavior.cs:line 48
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.ApplyIncomingTransportMessageMutatorsBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\MessageMutator\ApplyIncomingTransportMessageMutatorsBehavior.cs:line 21
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.SubscriptionReceiverBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Subscriptions\MessageDrivenSubscriptions\SubscriptionReceiverBehavior.cs:line 32
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.UnitOfWorkBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\UnitOfWork\UnitOfWorkBehavior.cs:line 44
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.ChildContainerBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Behaviors\ChildContainerBehavior.cs:line 17
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.ProcessingStatisticsBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Monitoring\ProcessingStatisticsBehavior.cs:line 23
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.<>c__DisplayClass5.<InvokeNext>b__2() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 95
   at NServiceBus.AuditBehavior.Invoke(IncomingContext context, Action next) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Audit\AuditBehavior.cs:line 22
   at NServiceBus.BehaviorChain`1.InvokeNext(T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 109
   at NServiceBus.BehaviorChain`1.Invoke() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\BehaviorChain.cs:line 61
   at NServiceBus.Pipeline.PipelineExecutor.Execute[T](BehaviorChain`1 pipelineAction, T context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 129
   at NServiceBus.Pipeline.PipelineExecutor.InvokePipeline[TContext](IEnumerable`1 behaviors, TContext context) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 86
   at NServiceBus.Pipeline.PipelineExecutor.InvokeReceivePhysicalMessagePipeline() in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Pipeline\PipelineExecutor.cs:line 103
   at NServiceBus.Unicast.UnicastBus.TransportMessageReceived(Object sender, TransportMessageReceivedEventArgs e) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\UnicastBus.cs:line 827
   at NServiceBus.Unicast.Transport.TransportReceiver.OnTransportMessageReceived(TransportMessage msg) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 413
   at NServiceBus.Unicast.Transport.TransportReceiver.ProcessMessage(TransportMessage message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 344
   at NServiceBus.Unicast.Transport.TransportReceiver.TryProcess(TransportMessage message) in c:\BuildAgent\work\3206e2123f54fce4\src\NServiceBus.Core\Unicast\Transport\TransportReceiver.cs:line 230
   at NServiceBus.Azure.Transports.WindowsAzureServiceBus.AzureServiceBusDequeueStrategy.TryProcessMessage(Object obj) in c:\BuildAgent\work\2f57832e2eee436e\src\Transport\Receiving\AzureServiceBusDequeueStrategy.cs:line 137

**Comment by mythz** [comment]
Hi thanks for the StackTrace, but what type of "Cloud worker role"? basically I want to try to reproduce the issue on my side with the simplest example possible, what VS.NET Azure Template should I use?

**Comment by monchaio** [comment]
We used Cloud Service - Worker role as template however seems like this case is conflict between NServiceBus and ServiceStack. Not sure this is related about dependency injection or not.

**Comment by mythz** [comment]
Hi, I was able to trace the underlying Exception to a  `AccessViolationException` which after some research suggests it's due to Data Execution Protection (DEP) being enabled, I was able to Remote Desktop into the Worker Role and turn it off by going to:

    Computer > 
      Properties > 
          Advanced System Settings > 
              Advanced > 
                  Performance [Settings] > 
                      Date Execution Protection > 

Then click the first radio button: **Turn on DEP for essential Windows Programs and services only**

![turn-off-dep](https://cloud.githubusercontent.com/assets/89361/9106311/df191618-3c51-11e5-9440-6be0b72effd4.png)

After restarting the Worker Role to take effect I was able to successfully Register the License Key.

Can you let me know if this works?

**Comment by monchaio** [comment]
Hi @mythz  on my local machine with OS Windows 8.1 This DEP feature default value is "Turn on DEP for essential Windows programs and services only" from the very beginning and I face stack trace above through Azure Compute Emulator. One other thing is my application use NLog to write any log to file system and log is written successfully. So I don't think this relate with DEP feature. Could you help me investigate more please.

**Comment by mythz** [comment]
To progress any further I will need to be able to reproduce the issue. 

Can you please put together the simplest stand-alone example that does reproduce the issue, either as a single Worker class (I can manually fetch any NuGet dependencies) or if it requires any configuration, please send a link to a new GitHub repo with the project I can publish/run to see the issue.

**Comment by monchaio** [comment]
Hi @mythz to make standalon project I need time due to our project is quite complex and extract some code is not easy. When I could reproduce it I will send you a link later.

**Comment by monchaio** [comment]
Hi @mythz now I can create solution that reproduce this error successfully.
You can download code from link https://github.com/monchaio/sample.
You need VS 2013 to open it and please also install Azure SDK 2.6 libraries.
Then please follow below step to see error.
1) Open Itq.Legal.Tenant.sln solution file
2) Set project ItqLegalTenantCloud as startup project
3) Set break point at WorkerRole.cs file under Itq.Legal.CommandHandlers.Tenant project at line
- ServiceStack.Licensing.RegisterLicense(@"<Your License>");
4) You will see exception thrown from ServiceStack.LicenseUtils

If you have any questions please lets me know.

**Comment by mythz** [comment]
Hi thanks for this, I was having issues trying to get this to run, (even after re-installing VS 2013 and Azure SDK 2.6 in a Windows VM), there seems to be an issue with the initializer for `new NServiceBusRoleEntrypoint()` which failed with a runtime exception: 

![nsb-error](https://cloud.githubusercontent.com/assets/89361/9203075/f32a5a8e-4022-11e5-92d9-1e2a03e04391.png)

Which was strange since AutoMapper.dll was there and the project builds fine. Trying to publish the project on Azure also failed with: 

![azure-publish-error](https://cloud.githubusercontent.com/assets/89361/9203135/3b21edf2-4023-11e5-805d-2af9ab303944.png)

Again strange because all the dependencies were there. Luckily I didn't need `NServiceBusRoleEntrypoint` to repro the error and was able to run it with it commented out, however when debugging it with the latest source code it ran without issue :)

So the solution is just to upgrade each of the projects to use [v4.0.43 that's on MyGett](https://github.com/ServiceStack/ServiceStack/wiki/MyGet), can you try this and let me know if it resolves the issue?

**Comment by monchaio** [comment]
Hi @mythz I still face the same error even though I've upgrade to ServiceStack 4.0.43. However I found root cause already. To solve this issue I need to re-reference ServiceStack.Text with from below folder only
packages\ServiceStack.Text\lib\net40\ServiceStack.Text.dll

If we reference library from 
packages\ServiceStack.Text\lib\portable-net45+win8+monotouch+monoandroid+xamarin.ios10\ServiceStack.Text.dll

We will face this error log under Azure worker role anyway.
However thank you so much for your help to analyst this issue.

**Comment by mythz** [comment]
Ok great glad you've discovered the issue. But it's strange that it's referencing the PCL packages, I've uninstalled/reinstalled the ServiceStack NuGet package and it appears to reference the `/net40/ServiceStack.Text.dll` version as expected. 

Incidentally this issue always happen for the PCL ServiceStack.Text dlls as the implementation providers for the [different PCL client platforms](https://github.com/ServiceStackApps/HelloMobile#portable-class-library-support) are maintained in the **ServiceStack.Client** package, which is needed to be able to use ServiceStack.Text in PCL platforms.
