### ISSUE TITLE
v. 4.0.46 error Reference to type 'IRequiresSchema' 

### ISSUE THREAD

**Issue by stefan2410** [ServiceStack/Issues#361]
After updating to  4.0.46 from 4.0.44, we get this error
Severity Code Description Project File Line
Error CS7069 Reference to type 'IRequiresSchema' claims it is defined in 'ServiceStack', but it could not be found GRM.SERVICE.API D:\src\Workspaces\GRM.SERVICE.API\AppHost.cs 138
My team member reports that error disappears if we comment the Auth code
line 138:
         container.Register<IUserAuthRepository>(c =>
         new OrmLiteAuthRepository(c.Resolve<IDbConnectionFactory>()));
         ConfigureAuth();

the same error appear  in  line container.Register<ICacheClient>(dbCacheClient);
Is there a breaking change ?

**Comment by mythz** [comment]
`IRequiresSchema` was defined in ServiceStack.dll but was moved to ServiceStack.Interfaces.dll so it could be shared, but it kept the same `ServiceStack` namespace and everything should already be referencing ServiceStack.Interfaces so this change shouldn't be noticeable after a recompile.

**Comment by stefan2410** [comment]
We have cleaned and rebuilt but the error continues

**Comment by stefan2410** [comment]
Ok, we updated all libraries (Ormlite.SqlServer 4.0.42 to 4.0.46)  and the problem was fixed. 
Then we had other problem, that the AppHost did not regognize  types in our ServiceInterface.
Our ServiceInterface uses razorgenerator. build task.
It seems that when we rebuild   the project that has the dependency,
it  tries  to rebuild the the dependent project wihich uses razorgenerator , 
and we get an error as you can see in the end
My team member reports
  " solution: it works correct if we compile dependent project first, and then the project which has the dependency  "

Stack Trace
Severity Code Description Project File Line
Error  The "RazorGeneratorBuildTask" task failed unexpectedly.
System.ArgumentNullException: Value cannot be null.
Parameter name: fileName
   at System.IO.FileInfo..ctor(String fileName)
   at ServiceStack.HostContext.GetAppConfigPath()
   at ServiceStack.HostConfig.get_RazorNamespaces()
   at ServiceStack.Razor.Compilation.CodeTransformers.WebConfigTransformer.Initialize(RazorPageHost razorHost, IDictionary`2 directives)
   at ServiceStack.Razor.Compilation.CodeTransformers.AggregateCodeTransformer.Initialize(RazorPageHost razorHost, IDictionary`2 directives)
   at ServiceStack.Razor.Managers.RazorGen.RazorViewPageTransformer.Initialize(RazorPageHost razorHost, IDictionary`2 directives)
   at ServiceStack.Razor.Compilation.CodeTransformers.RazorCodeTransformerBase.ServiceStack.Razor.Compilation.IRazorCodeTransformer.Initialize(IRazorHost razorHost, IDictionary`2 directives)
   at ServiceStack.Razor.Compilation.RazorPageHost.Generate()
   at ServiceStack.Razor.Compilation.RazorPageHost.GenerateSourceCode()
   at ServiceStack.Razor.BuildTask.RazorGeneratorBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext() grm.service.ServiceInterface

**Comment by mythz** [comment]
I don't know how you've got your project structured but the error message says it's looking for a Web.config or your exe .config in [HostContext.GetAppConfigPath](https://github.com/ServiceStack/ServiceStack/blob/master/src/ServiceStack/HostContext.cs#L205), this is what contains the list of C# namespaces that should included in the compiled Razor pages.

**Comment by stefan2410** [comment]
thanks , we had an app.config, as the GetAppConfigPath looks for {0}.config also.
When we added it and an  web.config  it worked.
