### ISSUE TITLE
OrmLite Single<T> changes behavior with UseParameterizeSqlExpressions = true default from 4.0.52

### ISSUE THREAD

**Issue by rsafier** [ServiceStack/Issues#393]
We have the following code that had been working, and still works with 
`UseParameterizeSqlExpressions = false;`. 

    var query = conn.From<Panther.OrmLite.CustomerDB.Customer>();
    if (!BackOfficeCustomerNo.IsNullOrEmpty())
    {
        query = query.Where(t => t.BackOfficeCustomerNo == BackOfficeCustomerNo);
    } else {
        query = query.Where(t => t.IntransCustomerNo == IntransCustomerNo); 
    }
                    var select = query.Select(q => new
                    {
                        IntransCustomerNo = q.IntransCustomerNo,
                        BillToNo = q.BillToNo,
                        BackOfficeCustomerNo = q.BackOfficeCustomerNo,
                        CustomerName = q.CustomerName
                    });
                    var data = conn.Single<UCMCustomerNos>(select);

When run under .52 defaults you receive a  `Must declare the scalar variable "@0".` exception from SqlServer. It works correctly as `Select<UCMCustomerNos>`, but I only wish to have the 1st record. 

Stacktrace:
`
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at ServiceStack.OrmLite.OrmLiteCommand.ExecuteReader()
   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.ExecReader(IDbCommand dbCmd, String sql)
   at ServiceStack.OrmLite.OrmLiteResultsFilterExtensions.ConvertTo[T](IDbCommand dbCmd, String sql)
   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.Single[T](IDbCommand dbCmd, String sql, Object anonType)
   at ServiceStack.OrmLite.OrmLiteReadExpressionsApi.<>c__DisplayClass22`1.<Single>b__21(IDbCommand dbCmd)
   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)
   at ServiceStack.OrmLite.OrmLiteReadExpressionsApi.Exec[T](IDbConnection dbConn, Func`2 filter)
   at ServiceStack.OrmLite.OrmLiteReadExpressionsApi.Single[T](IDbConnection dbConn, ISqlExpression expression, Object anonType)
   at Panther.Providers.AFBookingEngine.DB.DBLogic.GetUCMCustomerData(String BackOfficeCustomerNo, String IntransCustomerNo)
`

**Comment by rsafier** [comment]
It looks like #392 already is expressing my issue and its already taken care of.

**Comment by mythz** [comment]
yep should be resolved, but let me know if it's not.

**Comment by rsafier** [comment]
Prerelease .53 works as expected.
