### ISSUE TITLE
ServiceStack.Redis: "Unable to Connect: sPort: 0" and Unable to cast object of type 'System.Byte[]' to type 'System.Object[]'

### ISSUE THREAD

**Issue by Joe-U-Questionmark** [ServiceStack/Issues#465]
I have a test harness that repeatedly gets and sets DateTime objects so we can test fail-over of our new Redis Sentinel deployment. 

I have added my license key to the static constructor of the calling class.

I have not made any client configuration so it should be using the defaults.

Gets and Sets succeed 99% of the time but I am getting intermittent failures like the ones below. 

1. Unable to Connect: sPort: 0

    ServiceStack.Redis.RedisException: Unable to Connect: sPort: 0
       at ServiceStack.Redis.RedisNativeClient.CreateConnectionError()
       at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
       at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs)
       at ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(String masterName)
       at ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(String masterName)

 Other posts claim this could be related to the ConnectTimeout, but we are not setting it specifically and therefore the default (-1 / not set) should be being used. 
 What is the issue?
    
2 . Unable to cast object of type 'System.Byte[]' to type 'System.Object[]'

    2016-07-15 15:00:04,825 ERROR Caching.CacheCore.RedisCacheCore - Get<T> failed with key @#qm:qmth:testhardness-3be0f6bb-5df5-4205-afe4-45ee56b59a71
    2016-07-15 15:00:04,825 ERROR Tools.RedisTestHarness.Program - READ - EXCEPTION [Duration: 00:00:00.4976532]: Unable to cast object of type 'System.Byte[]' to type 'System.Object[]'.
    2016-07-15 15:00:04,825 DEBUG Tools.RedisTestHarness.Program -    at System.Linq.Enumerable.<CastIterator>d__1`1.MoveNext()
       at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
       at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
       at ServiceStack.Redis.RedisNativeClient.SentinelSlaves(String masterName)
       at ServiceStack.Redis.RedisSentinelWorker.GetSlaveHosts(String masterName)
       at ServiceStack.Redis.RedisSentinelWorker.GetSentinelInfo()
       at ServiceStack.Redis.RedisSentinel.GetSentinelInfo()
       at ServiceStack.Redis.RedisSentinel.GetRedisManager()
       at ServiceStack.Redis.RedisSentinel.GetValidSentinelWorker()
       at ServiceStack.Redis.RedisSentinel.Start()
       at Caching.CacheCore.RedisCacheCore.CreateManagerForSentinel(String connectionString, String sentinelHostFilter)
       at Caching.CacheCore.RedisCacheCore.CreateClientManager(String connectionString, Boolean useSentinel, String sentinelHostFilter)
       at Caching.CacheCore.RedisCacheCore.GetClient()
       at Caching.CacheCore.RedisCacheCore.Get[T](String key)
       at Caching.CacheCore.CacheCoreWrapper.<>c__DisplayClass1`1.<Get>b__0()
       at Caching.FunctionHandlers.ExecuteFunctionHandler.HandleFunction[T](Func`1 functionToHandle)
       at Caching.CacheCore.CacheCoreWrapper.Get[T](String key)
       at Caching.Cache.Get[T](String key)
       at Tools.RedisTestHarness.Program.Main(String[] args) in ...\Tools.RedisTestHarness\Program.cs:line 123

   
 This makes no sense to me. Any ideas?
 
Both of these issues are preventing us from deploying to production.

Thanks for your help in advance.

**Comment by mythz** [comment]
The first error suggests the client is unable to connect to the server, and the second error suggests the server returned an unexpected response which can happen if you're using the same client instance across multiple threads (i.e. instead of retrieving a new client from the pool in each thread). 

But we'd need a small, stand-alone repro to identify the issue. Can you provide a small, stand-alone repro of the issue, if it's in one file you can post it here, otherwise can you put it in a new Github repository?

**Comment by Joe-U-Questionmark** [comment]
I have significantly reduced the frequency of the errors occurrence. 
The code to make the IRedisClientsManager a singleton was failing so the code was effectively like the following:
  for (int i = 0; i < 10000000; i++)
            {
                using (var cache = CreateManager().GetClient())
                {
                    cache.Set<string>("key", "value");
                    cache.Get<string>("key");
                }
                Thread.Sleep(10);
            }
            

        IRedisClientsManager CreateManager()
        {
            return new RedisSentinel(sentinelList, MASTER_NAME).Start();
        }

I am now storing the IRedisClientsManager in a ConcurrentDictionary keyed by the connection string details but I find if I start my test harness 1 time out of 20 I still get the error on first launch. Any ideas? The code is currently in a single threaded console application.

**Comment by xplicit** [comment]
That's looks strange that you create manager every time in a loop. It should be created once and then get the client from it on every operation. Is the following code not working for you?

        static void Main(string[] args)
        {
           var manager =  new RedisSentinel(sentinelList, MASTER_NAME).Start();

            for (int i = 0; i < 10000000; i++)
            {
                using (var cache = manager.GetClient())
                {
                    cache.Set<string>("key", "value");
                    cache.Get<string>("key");
                }
                Thread.Sleep(10);
            }
        }

**Comment by Joe-U-Questionmark** [comment]
The code sample that I gave was what was effectively happening before I made the fix to my ConcurrentDictionary code. Now my code is effectively the same as your code sample but I am still experiencing the issue on the first set 1 in 20 times when I start the console app. 

In either setup should I really ever experience these errors as the code is single threaded?

**Comment by xplicit** [comment]
Do I correctly understand that you run exactly the same code sample as provided above without any additional code and sometimes you've got an error on start?

**Comment by mythz** [comment]
@Joe-U-Questionmark Can you please provide us with a small, stand-alone example of the code you're running that causes the errors you're seeing, creating a new sentinel in a loop as done in your first example is invalid, there should only ever be 1 instance of `RedisSentinel` started as seen in @xplicit's example.

**Comment by mythz** [comment]
If there's still an issue with valid usage of the `RedisSentinel` client please reply with the code we can run to repro the issue.

**Comment by Joe-U-Questionmark** [comment]
I have one. Do you have an email address I can send it to?

**Comment by mythz** [comment]
If the code isn't small enough to fit here, can you publish it in a new Github repo?

**Comment by mythz** [comment]
I've received the code and configured it to run locally, but I can't reproduce the error with this code after baby sitting several times with multiple instances running. I eventually see an error because you're setting a expiry with your cache entry, i.e:

var success = cache.Set(key, valueToSet ,TimeSpan.FromMinutes(5));

So eventually after 5 mins each instance will eventually no longer be able to retrieve the value that's automatically expired. So your App starts to log errors even though it's working as intended.

Note this code hammers the Redis instance, more so when multiple apps are running so even though it's rare, the redis server is going to eventually deny client TCP connections at which point the client wont be able to connect and end up throwing the `Unable to Connect` error you've seen, but what happens after that point? i.e. are you able to re-connect to the redis server in subsequent calls to redis?

**Comment by Joe-U-Questionmark** [comment]
>So eventually after 5 mins each instance will eventually no longer be able to retrieve the value

You can change that behaviour by setting  <add key="SetUpdatedValueEachLoop" value="true" />.

> The redis server is going to eventually deny client TCP connections at which point the client wont be able to connect and end up throwing the Unable to Connect error you've seen

This sometimes happens as soon as we start the test harness so I don't think it can be attributed to TCP connections being exhausted. 

I cannot reproduce the error on a 1 server setup either only when connecting to a 3 sentinels with 1 master and 2 slaves setup.

>The first error suggests the client is unable to connect to the server, and the second error suggests the server returned an unexpected response which can happen if you're using the same client instance across multiple threads 

So you can see that I am not using the same instance across multiple threads as this is a single threaded application. If issue 1 means "Connection error" can you explain issue 2 in my context?

Thanks again for your help.

**Comment by mythz** [comment]
I've added some additional logging with timestamps when the client is unable to connect in [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/c77219f73fadf0216ff4b63d3ddb61ad900d03cd) and for when the Sentinel Worker receives an invalid response in [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/c17a62b4eeae59f5bbc4f1846bb5bb235f2efe11) which will hopefully tell us what the invalid response it receives is instead.

This change is available from v4.0.61 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

**Comment by Joe-U-Questionmark** [comment]
Thanks for that. QA reproduced the issue 3 times:

```
2016-08-01 12:13:43,478 DEBUG QM.Caching.CacheCore.RedisCacheCore - Calling Set with key @#qm:qmth:testhardness-a434861f-ce0e-49e7-b8b2-10d9bf22f8f0 value 8/1/2016 12:13:43 PM and ttl
2016-08-01 12:13:43,603 ERROR QM.Caching.CacheCore.RedisCacheCore - Redis Worker error
ServiceStack.Redis.RedisException: [12:13:43.603] Unable to Connect: sPort: 0, Error: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx)
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(String masterName)

---
  2016-08-01 12:08:02,703 DEBUG QM.Caching.CacheCore.RedisCacheCore - Calling Get<T> with key @#qm:qmth:testhardness-9206a681-424b-41e3-bd52-5b2f85602c6d
2016-08-01 12:08:02,703 ERROR QM.Caching.CacheCore.RedisCacheCore - Redis Worker error
ServiceStack.Redis.RedisException: [12:08:02.703] Unable to Connect: sPort: 0, Error: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx)
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(String masterName)
   
 ---
 
   2016-08-01 12:25:50,017 DEBUG QM.Caching.CacheCore.RedisCacheCore - Calling Set with key @#qm:qmth:testhardness-e2b82d9f-8130-4eec-868c-910083c6287b value 8/1/2016 12:25:50 PM and ttl
2016-08-01 12:25:50,017 ERROR QM.Caching.CacheCore.RedisCacheCore - Redis Worker error
ServiceStack.Redis.RedisException: [12:25:50.017] Unable to Connect: sPort: 0, Error: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx)
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectDeeplyNestedMultiData(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.SentinelSlaves(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetSlaveHosts(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetSentinelInfo()
   at ServiceStack.Redis.RedisSentinel.GetSentinelInfo()
   at ServiceStack.Redis.RedisSentinel.GetRedisManager()
   at ServiceStack.Redis.RedisSentinel.GetValidSentinelWorker()
```

**Comment by mythz** [comment]
Unfortunately it doesn't contain the StackTrace of the inner Exception which I've added in [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/1336536b16ab306c6a47b5e59a30391d1461029c). 

This change is now on MyGet. Since you already have v4.0.61 installed you'll need to [clear your NuGet cache](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages) in order to download this latest version.

**Comment by Joe-U-Questionmark** [comment]
Here are some errors to look at with stack traces. I have also attached the event logs from the EventLogFactory.

```

2016-08-02 12:47:31,852 DEBUG QM.Caching.CacheCore.RedisCacheCore - Calling Get<T> with key @#qm:qmth:testhardness-ad5ff81c-e7b7-4804-bb8f-11516c67b920
2016-08-02 12:47:31,821 ERROR QM.Caching.CacheCore.RedisCacheCore - Redis Worker error
ServiceStack.Redis.RedisException: [12:47:31.821] Unable to Connect: sPort: 0, Error: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer()
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer()
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx)
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(String masterName)
   
   2016-08-02 12:47:39,742 DEBUG QM.Caching.CacheCore.RedisCacheCore - Calling Get<T> with key @#qm:qmth:testhardness-ad5ff81c-e7b7-4804-bb8f-11516c67b920
2016-08-02 12:47:39,742 ERROR QM.Caching.CacheCore.RedisCacheCore - Redis Worker error
ServiceStack.Redis.RedisException: [12:47:39.742] Unable to Connect: sPort: 0, Error: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer()
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer()
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx)
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(String masterName)

   2016-08-02 12:47:40,367 DEBUG QM.Caching.CacheCore.RedisCacheCore - Calling Get<T> with key @#qm:qmth:testhardness-ad5ff81c-e7b7-4804-bb8f-11516c67b920
2016-08-02 12:47:40,383 ERROR QM.Caching.CacheCore.RedisCacheCore - Redis Worker error
ServiceStack.Redis.RedisException: [12:47:40.383] Unable to Connect: sPort: 0, Error: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer()
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer()
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx)
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(String masterName)
   
   
2016-08-02 12:47:40,492 ERROR QM.Tools.RedisTestHarness.Program - WRITE - EXCEPTION [Duration (ms): 1284]: 
System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at ServiceStack.Redis.RedisExtensions.ToRedisEndpoint(String connectionString, Nullable`1 defaultPort)
   at ServiceStack.Redis.RedisExtensions.<ToRedisEndPoints>b__0(String x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ServiceStack.Redis.RedisExtensions.ToRedisEndPoints(IEnumerable`1 hosts)
   at ServiceStack.Redis.PooledRedisClientManager..ctor(IEnumerable`1 readWriteHosts, IEnumerable`1 readOnlyHosts, RedisClientManagerConfig config, Nullable`1 initalDb, Nullable`1 poolSizeMultiplier, Nullable`1 poolTimeOutSeconds)
   at ServiceStack.Redis.RedisSentinel.<.ctor>b__0(String[] masters, String[] slaves)
   at ServiceStack.Redis.RedisSentinel.CreateRedisManager(SentinelInfo sentinelInfo)
   at ServiceStack.Redis.RedisSentinel.GetRedisManager()
   at ServiceStack.Redis.RedisSentinel.GetValidSentinelWorker()
   at ServiceStack.Redis.RedisSentinel.Start()
   at QM.Caching.CacheCore.RedisCacheCore.CreateManagerForSentinel(String connectionString, String sentinelHostFilter) in D:\tfs\Core\Shared\main\solutions\src\QM.Caching\CacheCore\RedisCacheCore.cs:line 136
   at QM.Caching.CacheCore.RedisCacheCore.GetClient() in D:\tfs\Core\Shared\main\solutions\src\QM.Caching\CacheCore\RedisCacheCore.cs:line 89
   at QM.Caching.CacheCore.RedisCacheCore.Set[T](String key, T item, TimeSpan ttl) in 
   
   
   2016-08-02 12:48:23,067 ERROR QM.Caching.CacheCore.RedisCacheCore - Redis Worker error
ServiceStack.Redis.RedisException: [12:48:23.067] Unable to Connect: sPort: 0, Error: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer()
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ServiceStack.Redis.RedisNativeClient.FlushSendBuffer()
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.CreateConnectionError(Exception originalEx)
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(String masterName)

```
[Eventlogs.zip](https://github.com/ServiceStack/Issues/files/397081/Eventlogs.zip)

**Comment by mythz** [comment]
The only thing that I can see that can be null in `FlushSendBuffer()` is `socket` which I'm now guarding against in [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/844da9e5ee14525542dfcb8b3234f21d2f209376) so it should throw before it reaches `FlushSendBuffer()` and reconnect as part of the normal auto retry fallback.

For the invalid/unexpected response it looks like the client only received a partial response from the server. I've changed it to use a different parsing implementation in [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/731283f68e1cd9069f15322a91dd085c60c7957c) which will prevent it from having casting errors it had previously but can still throw if it receives an invalid response.

This change is now on MyGet, you'll still need to [clear your NuGet cache](https://github.com/ServiceStack/ServiceStack/wiki/MyGet#redownloading-myget-packages) to get the latest version.

**Comment by Joe-U-Questionmark** [comment]
There are 2 types of error in the logs now. So the messages are now clearer but what is their cause?

Also the event logs are full of errors: 
[EventLogs2ndAttempt.zip](https://github.com/ServiceStack/Issues/files/399504/EventLogs2ndAttempt.zip)
```
2016-08-03 09:56:23,872 ERROR QM.Caching.CacheCore.RedisCacheCore - Redis Worker error
ServiceStack.Redis.RedisException: Exceeded timeout of 00:00:03 ---> ServiceStack.Redis.RedisRetryableException: Socket is not connected
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetMasterHost(String masterName)

2016-08-03 09:56:31,434 ERROR QM.Tools.RedisTestHarness.Program - WRITE - EXCEPTION [Duration (ms): 10878]: 
System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
   at ServiceStack.Redis.RedisExtensions.ToRedisEndpoint(String connectionString, Nullable`1 defaultPort)
   at ServiceStack.Redis.RedisExtensions.<ToRedisEndPoints>b__0(String x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ServiceStack.Redis.RedisExtensions.ToRedisEndPoints(IEnumerable`1 hosts)
   at ServiceStack.Redis.PooledRedisClientManager..ctor(IEnumerable`1 readWriteHosts, IEnumerable`1 readOnlyHosts, RedisClientManagerConfig config, Nullable`1 initalDb, Nullable`1 poolSizeMultiplier, Nullable`1 poolTimeOutSeconds)
   at ServiceStack.Redis.RedisSentinel.<.ctor>b__0(String[] masters, String[] slaves)
   at ServiceStack.Redis.RedisSentinel.CreateRedisManager(SentinelInfo sentinelInfo)
   at ServiceStack.Redis.RedisSentinel.GetRedisManager()
   at ServiceStack.Redis.RedisSentinel.GetValidSentinelWorker()
   at ServiceStack.Redis.RedisSentinel.Start()
   at QM.Caching.CacheCore.RedisCacheCore.CreateManagerForSentinel(String connectionString, String sentinelHostFilter) in 
```

**Comment by mythz** [comment]
The "Exceeded timeout of 00:00:03" means that the Redis Client was unable to open a TCP connection beyond the [Auto Retry default limit](https://github.com/ServiceStack/ServiceStack.Redis#automatic-retries) and so has no other option but to throw. In this case it looks like it's the Sentinel Worker was unable to connect to the Redis Sentinel instance.

This looks like the cause for most of the error messages, the Redis Sentinel server was either down or refused to accept new connections, so eventually all clients trying to reconnect will exceeded the Auto Retry limit and resulted in this error.

**Comment by Joe-U-Questionmark** [comment]
So do you think the change in error behaviour is that now you are throwing a `RedisRetryableException("Socket is not connected");` and therefore the client is now retrying so we don't see 
`ServiceStack.Redis.RedisException: Unable to Connect: sPort: 0, Error: Object reference not set to an instance of an object.` which wouldn't have caused a retry? 

Also can you explain this one?
```
System.ArgumentNullException: Value cannot be null.
Parameter name: connectionString
```

**Comment by mythz** [comment]
Yes, the retry is behaving as expected.

The 2nd Exception was a result from the Sentinel Worker not being able to get the Address of the Master Redis instance from the Sentinel. Previously the exception was caught and returned null which was passed down when initializing the Sentinel's internal Redis Client Manager. The Exception now gets bubbled in [this commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/319aaae3d92ecc39da6aeadc109da89daa525c84) and treated as a failure.

This change is now available on [MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

Let me know if the autoretry timeout is the only error remaining?

**Comment by Joe-U-Questionmark** [comment]
This is the only entry in my log:

2016-08-04 14:22:35,345 ERROR QM.Caching.CacheCore.RedisCacheCore - Redis Worker error
ServiceStack.Redis.RedisException: Exceeded timeout of 00:00:03 ---> ServiceStack.Redis.RedisRetryableException: Socket is not connected
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectMultiData(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.SentinelGetMasterAddrByName(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetMasterHostInternal(String masterName)
   at ServiceStack.Redis.RedisSentinelWorker.GetSentinelInfo()
   at ServiceStack.Redis.RedisSentinel.GetSentinelInfo()
   at ServiceStack.Redis.RedisSentinel.GetRedisManager()
   at ServiceStack.Redis.RedisSentinel.GetValidSentinelWorker()

But the event logs are still busy (but mainly with timeouts):

[EventLogs3rdAttempt.zip](https://github.com/ServiceStack/Issues/files/401990/EventLogs3rdAttempt.zip)

I think that is all the issues? 
1. Why do you think we experienced these issues but no one else was reporting them?
2. When do you plan on pushing that version to nuget instead of myget? (We would prefer to run a "supported" version in production)

Thanks for your help!

**Comment by mythz** [comment]
ok so this is the expected behavior, the redis client can't connect to the redis-server within the default AutoRetry limit so it eventually throws.

I'm assuming you're overloading your redis-server instance, maybe it doesn't have enough RAM, CPU, etc. I didn't get these errors running your App, but if I open enough instances all hammering the same instance it will. If you're testing against a Windows redis-server instance you can try disabling persistence as forking isn't implemented efficiently in Windows.

We're hoping to deploy next week, but our pre-release MyGet is also supported - they're run through the same test suite and is no different to the official NuGet packages other than when it's released.
