### ISSUE TITLE
SqlServer2012OrmLiteDialectProvider and geography type

### ISSUE THREAD

**Issue by Savvkin** [ServiceStack/Issues#474]
Hello,
If I try to delete the instance of the class that contains SqlGeography property using the delete method:
```
conn.Delete(obj);
```
I get an exception:

```
System.Data.SqlClient.SqlException (0x80131904): Invalid operator for data type. Operator equals equal to, type equals geography.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at ServiceStack.OrmLite.OrmLiteCommand.ExecuteNonQuery()
   at ServiceStack.OrmLite.OrmLiteResultsFilterExtensions.ExecNonQuery(IDbCommand dbCmd)
   at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.AssertRowsUpdated(IDbCommand dbCmd, Boolean hadRowVersion)
   at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Delete[T](IDbCommand dbCmd, Object anonType)
   at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Delete[T](IDbCommand dbCmd, T anonType)
   at ServiceStack.OrmLite.OrmLiteWriteApi.<>c__DisplayClass1c`1.<Delete>b__1b(IDbCommand dbCmd)
   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)
   at ServiceStack.OrmLite.OrmLiteReadExpressionsApi.Exec[T](IDbConnection dbConn, Func`2 filter)
   at ServiceStack.OrmLite.OrmLiteWriteApi.Delete[T](IDbConnection dbConn, T allFieldsFilter)
...
ClientConnectionId:15071111-4eaa-4313-acea-1154779b8e4a
Error Number:403,State:1,Class:16
```

As a workaround I currently use following code:
```
var id = ((IHasId<int>)obj).Id;
conn.DeleteById<T>(id);
```

It happens to me after recent v3 to v4 upgrade.
Thanks.

**Comment by mythz** [comment]
This issue is because `SqlGeography` is a non-standard DB Type which doesn't behave like normal db params and follow the normal test for equality, i.e `field=@value`. It instead need to emit Custom SQLServer specific SQL to get the expected behavior, i.e `field.STEquals(@value) = 1`.

Which OrmLite is now doing from this commit: https://github.com/ServiceStack/ServiceStack.OrmLite/commit/824fb168e8d8a49ce413d3711191b99ea96ba00a

This change is available from v4.5.1 that's now [available on MyGet](https://github.com/ServiceStack/ServiceStack/wiki/MyGet).

P.S. you can also fetch the id from any POCO with the `GetId()` extension method, e.g:

```csharp
conn.DeleteById<T>(obj.GetId());
```

**Comment by Savvkin** [comment]
Thanks!
But it's a good idea to fix SqlGeometry too.

**Comment by Savvkin** [comment]
Hello again. I've updated from 4.0.62 to 4.5.4 and now Update crashes for calsses with SqlGeography with similar error:

```
System.Data.SqlClient.SqlException, System.Data
Incorrect syntax near '='.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at ServiceStack.OrmLite.OrmLiteWriteCommandExtensions.Update[T](IDbCommand dbCmd, T obj)
   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)
```

**Comment by KevinHoward** [comment]
@Savvkin, are you using the [b]ServiceStack.OrmLite.Converters.SqlServer[/b] library to handle the conversion to and from SqlGeography? I didn't see any mention of it.

I haven't attempted to write a unit test to the resolve the issue, but if you have some simple code handy that'd be great. If not, I can create something from the information provided.

**Comment by Savvkin** [comment]
Hello. Yes, I use copy of `SqlServerGeographyTypeConverter` from `ServiceStack.OrmLite.Converters.SqlServer`, since I need to work with most recent `SqlServerSpatial130.dll`.

I've created complete test, that reproduce the problem:
```csharp
[TestClass]
public class SqlGeographyTest
{
    #region Init
    [DllImport("kernel32.dll", CharSet = CharSet.Auto, SetLastError = true)]
    private static extern IntPtr LoadLibrary(string libname);

    private static void InitSqlServerSpatial(string root)
    {
        var path = IntPtr.Size > 4
            ? Path.Combine(root, @"SqlServerSpatial\x64\")
            : Path.Combine(root, @"SqlServerSpatial\x86\");

        var dll = Path.Combine(root, path, "msvcr120.dll");

        if (LoadLibrary(dll) == IntPtr.Zero)
            throw new Exception($"Error loading {dll} (ErrorCode: {Marshal.GetLastWin32Error()})");

        dll = Path.Combine(root, path, "SqlServerSpatial130.dll");
        if (LoadLibrary(dll) == IntPtr.Zero)
            throw new Exception($"Error loading {dll} (ErrorCode: {Marshal.GetLastWin32Error()})");
    }

    public static void InitServiceStack(string root)
    {
        JsConfig.AlwaysUseUtc = true;
        JsConfig.AssumeUtc = true;
        JsConfig.IncludeNullValues = false;
        CsvConfig.ItemSeperatorString = ";";

        InitSqlServerSpatial(root);

        OrmLiteConfig.DialectProvider = new SqlWithSqlGeographyTypeConverterOrmLiteDialectProvider();
    }
    #endregion

    public class SqlWithSqlGeographyTypeConverterOrmLiteDialectProvider : SqlServer2012OrmLiteDialectProvider
    {
        public SqlWithSqlGeographyTypeConverterOrmLiteDialectProvider()
        {
            this.GetDateTimeConverter().DateStyle = DateTimeKind.Utc;
            this.GetStringConverter().UseUnicode = true;
            this.GetStringConverter().StringLength = int.MaxValue;
            Converters.Add(typeof(SqlGeography), new SqlServerGeographyTypeConverter());
        }
    }

    public class ModelWithSqlGeography
    {
        [AutoIncrement]
        public int Id { get; set; }
        public string Name { get; set; }
        public DateTime Created { get; set; }
        public DateTime? Edited { get; set; }
        public SqlGeography Geo { get; set; }
    }

    [TestMethod]
    public void Model_with_SqlGeography_insert_and_update_works()
    {
        InitServiceStack(AppDomain.CurrentDomain.BaseDirectory);

        var connString = "";
        using (var conn = connString.OpenDbConnection())
            conn.DropAndCreateTable<ModelWithSqlGeography>();

        var wkt = "POINT(38.028495788574205 55.895460650576936)";
        using (var conn = connString.OpenDbConnection())
        {
            var obj = new ModelWithSqlGeography
            {
                Name = "Test",
                Created = DateTime.UtcNow,
                Geo = SqlGeography.STGeomFromText(new SqlChars(wkt), 4326)
            };

            var id = (int)conn.Insert(obj, selectIdentity: true);
            obj.Id = id;
            obj.Edited = DateTime.UtcNow;

            try
            {
                // Update of POCO with SqlGeography proprety should work
                conn.Update(obj);
            }
            catch (Exception ex)
            {
                Assert.Fail(ex.ToString());
            }
            finally
            {
                // GetLastSql shouldn't return null after exception
                var lastSql = conn.GetLastSql();
                Assert.IsNotNull(lastSql);
            }
        }
    }
}
```

**Comment by KevinHoward** [comment]
@Savvkin, I have sent a PR to fix the issue with the updating of SqlGeography fields in this commit [https://github.com/ServiceStack/ServiceStack.OrmLite/pull/547](https://github.com/ServiceStack/ServiceStack.OrmLite/pull/547). 

As for the GetLastSql() method returning null... this is due to an attempted cast from SqlConnection to OrmLiteConnection in OrmLiteWriteApi.cs line 19. To resolve this issue, make sure to initialize your connection using an OrmLiteConnectionFactory (i.e. `var conn = new OrmLiteConnectionFactory(ConnectionString, dialectProvider).OpenDbConnection();` ) so the SqlConnection gets wrapped and can use this extended functionality.

**Comment by mythz** [comment]
Thx @KevinHoward! Kevin's PR is now [available on MyGet](http://docs.servicestack.net/myget).
