### ISSUE TITLE
DateTime.MaxValue throws an error when serializing to JSON

### ISSUE THREAD

**Issue by mbiasetti** [ServiceStack/Issues#498]
Reproduce by calling the following code:
```
using ServiceStack.Text;
namespace Program
{
    void Main()
    {
        var date = DateTime.MaxValue.ToUnixTime();
    }
}

```
Result: 
```
{  
   "ErrorCode":"ArgumentOutOfRangeException",
   "Message":"The added or subtracted value results in an un-representable DateTime. Parameter name: value",
   "StackTrace":"   at System.DateTime.Subtract(TimeSpan value)
   at ServiceStack.Text.DateTimeExtensions.ToDateTimeSinceUnixEpoch(DateTime dateTime)
   at ServiceStack.Text.DateTimeExtensions.ToUnixTimeMs(DateTime dateTime)
   at ServiceStack.Text.Common.DateTimeSerializer.WriteWcfJsonDate(TextWriter writer, DateTime dateTime)
   at ServiceStack.Text.Json.JsonTypeSerializer.WriteDateTime(TextWriter writer, Object oDateTime)
   at ServiceStack.Text.Json.JsonTypeSerializer.WriteNullableDateTime(TextWriter writer, Object dateTime)
   at ServiceStack.Text.Common.WriteType`2.WriteProperties(TextWriter writer, Object value)
   at ServiceStack.Text.Common.WriteListsOfElements`2.WriteGenericIList(TextWriter writer, IList`1 list)
   at ServiceStack.Text.Common.WriteListsOfElements`2.WriteList(TextWriter writer, Object oList)
   at ServiceStack.Text.JsonSerializer.SerializeToStream(Object value, Type type, Stream stream)
   at ServiceStack.Text.JsonSerializer.SerializeToStream[T](T value, Stream stream)
   at ServiceStack.Serialization.JsonDataContractSerializer.SerializeToStream[T](T obj, Stream stream)
   at ServiceStack.Host.ContentTypes.<>c.<GetStreamSerializer>b__21_1(IRequest r, Object o, Stream s)
   at ServiceStack.Host.ContentTypes.<>c__DisplayClass20_0.<GetResponseSerializer>b__0(IRequest httpReq, Object dto, IResponse httpRes)
   at ServiceStack.HttpResponseExtensionsInternal.WriteToResponse(IResponse response, Object result, ResponseSerializerDelegate defaultAction, IRequest request, Byte[] bodyPrefix, Byte[] bodySuffix)",
   "Errors":[  
      {  
         "ErrorCode":"ArgumentOutOfRangeException",
         "FieldName":"value",
         "Message":"The added or subtracted value results in an un-representable DateTime."
      }
   ]
}
```

Workaround: Truncate time portion of DateTime

Environment: Windows 7, .NET 4+, recreated in LINQPad. ServiceStack Nuget v4.0.60

**Comment by mythz** [comment]
This should now be resolved with [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/39e36c2efede4e31b1d5aac7984f3987ae998a5b).

This fix is available from v4.5.5 that's now [available on MyGet](http://docs.servicestack.net/myget)
