### ISSUE TITLE
Exception when connecting with RedisNativeClient in .NET Core

### ISSUE THREAD

**Issue by thomfre** [ServiceStack/Issues#518]
After #514 was fixed, we tried turning on SSL again. We now get this exception when connecting to Redis in .NET Core:
```csharp
System.InvalidCastException: Unable to cast object of type 'System.Net.Security.SslStream' to type 'System.Net.Sockets.NetworkStream'.
 at ServiceStack.Redis.RedisNativeClient.Connect()
 at ServiceStack.Redis.RedisNativeClient.TryConnectIfNeeded()
 at ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
 at ServiceStack.Redis.RedisNativeClient.AssertServerVersionNumber()
 at ServiceStack.Redis.RedisClient.GetServerRole()
 at ServiceStack.Redis.RedisResolver.CreateRedisClient(RedisEndpoint config, Boolean master)
 at ServiceStack.Redis.RedisResolver.CreateMasterClient(Int32 desiredIndex)
 at ServiceStack.Redis.RedisManagerPool.GetClient()
 at ServiceStack.Redis.RedisClientManagerCacheClient.SetAll[T](IDictionary`2 values)
```

We tried both v1.0.34 and v1.0.35, same problem on both.

**Comment by xplicit** [comment]
The exception was fixed in this [commit](https://github.com/ServiceStack/ServiceStack.Redis/commit/bbf626e0c21525c374794cc8bc1381c64fabb18c) and ServiceStack.Redis v 1.0.36 with this fix is available on [nuget](https://www.nuget.org/packages/ServiceStack.Redis.Core/)
