### ISSUE TITLE
Bug in ServiceStack.Redis.RedisNativeClient.Ping()

### ISSUE THREAD

**Issue by ttotre** [ServiceStack/Issues#582]
Hi Team,

I am getting below error , while calling Ping() on RedisNativeClient. I have already checked that Redis service is up and Running. I am able to connect to Redis Server using Redis Client.

Using Redis Client is send Ping Command I am getting pong response.

But still below call fail on ServiceStack Library. Could you please check and advice.

ServiceStack.Redis.RedisException: Exceeded timeout of 00:00:10 ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 172.17.65.80:6379
   at System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   at System.Net.Sockets.Socket.Connect(String host, Int32 port)
   at ServiceStack.Redis.RedisNativeClient.Connect()
   at ServiceStack.Redis.RedisNativeClient.TryConnectIfNeeded()
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   --- End of inner exception stack trace ---
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead)
   at ServiceStack.Redis.RedisNativeClient.SendExpectCode(Byte[][] cmdWithBinaryArgs)
   at ServiceStack.Redis.RedisNativeClient.Ping()

**Comment by mythz** [comment]
The error message indicates that the client was unable to make a TCP connection to 72.17.65.80:6379 in which case I’m assuming then no Redis APIs work, I.e. not just Ping is that right? 

I’d be looking to see if you have a firewall blocking access to the Redis server from the computer where the Redis Client with this Exception is being used.
