### ISSUE TITLE
ServiceStack.OrmLite.MySqlConnector exception thrown when using transaction

### ISSUE THREAD

**Issue by mjdaly** [ServiceStack/Issues#608]
MySqlConnector is throwing an exception when using a transaction. It looks related to the transaction behaviour change mentioned in [this issue](https://github.com/mysql-net/MySqlConnector/issues/405).

**Exception**
```

System.InvalidOperationException : The transaction associated with this command is not the connection's active transaction.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at ServiceStack.OrmLite.OrmLiteResultsFilterExtensions.ConvertToList[T](IDbCommand dbCmd, String sql)
   at ServiceStack.OrmLite.OrmLiteReadCommandExtensions.Select[T](IDbCommand dbCmd, String sql, Object anonType)
   at ServiceStack.OrmLite.OrmLiteExecFilter.Exec[T](IDbConnection dbConn, Func`2 filter)
```

**Code**
```
using (var conn = connFactory_.OpenDbConnection())
{
    using (conn.BeginTransaction())
        conn.Select<int>("select 1");
}
```

**Libraries**
1. ServiceStack.OrmLite.MySqlConnector v5.0.2
1. MySqlConnector v0.33.2

**Comment by mythz** [comment]
You need to use [OpenTransaction()](https://github.com/ServiceStack/ServiceStack.OrmLite#transaction-support), e.g:

```csharp

using (var conn = connFactory_.OpenDbConnection())
{
    using (var trans = conn.OpenTransaction())
    {
        conn.Select<int>("select 1");
        trans.Commit();
    }
}
```

**Comment by mjdaly** [comment]
Ahh yes, apologies.
