### ISSUE TITLE
Getting Invalid ConditionExpression Exception while trying to use PocoDynamo Update Expression with Condition

### ISSUE THREAD

**Issue by vikram-panigrahi** [ServiceStack/Issues#611]
**Code**

    var updateFile = dynamoDb_.UpdateExpression<Types.File>(account_)
                        .Set(() => new Types.File
                        {
                            ModifiedUtc = DateTime.UtcNow
                        })
                        .Condition(f => f.Path.StartsWith(folderPath));

    dynamoDb_.UpdateItem(updateFile);

    [References(typeof(FilePathIndex))]
    [CompositeKey("Account", "S3Location")]
    public class File
    {
        public Guid Account { get; set; }
        public string S3Location { get; set; }
        public string Path { get; set; }
        public DateTime ModifiedUtc { get; set; }
    }

**Exception**

    Amazon.DynamoDBv2.AmazonDynamoDBException : Invalid ConditionExpression: An expression 
    attribute name used in the document path is not defined; attribute name: #PA
    ----> Amazon.Runtime.Internal.HttpErrorResponseException : Exception of type 
    'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
      at ServiceStack.TaskExt.GetResult(Task task)
      at ServiceStack.Aws.NetCoreAwsExtensions.UpdateItem(IAmazonDynamoDB client, 
    UpdateItemRequest request)
      at ServiceStack.Aws.DynamoDb.PocoDynamo.Exec[T](Func`1 fn, Type[] rethrowExceptions, HashSet`1 
    retryOnErrorCodes)
      at ServiceStack.Aws.DynamoDb.PocoDynamo.UpdateItem[T](UpdateExpression`1 update)
    --HttpErrorResponseException
      at Amazon.Runtime.HttpWebRequestMessage.<GetResponseAsync>d__20.MoveNext() in 
    E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestM 
    essageFactory.cs:line 443
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
    task)
       at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in 
    E:\JenkinsWorkspaces\v3-stage- 
    release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 
    175
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
    task)
        at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
     --- End of stack trace from previous location where exception was thrown ---
        at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task 
     task)
         at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()

**Libraries**

    1. ServiceStack.Aws - v5.0.3
    2. AWSSDK.DynamoDBv2 - v3.3.7.1

**Comment by mythz** [comment]
This should now be resolved with [this commit](https://github.com/ServiceStack/ServiceStack.Aws/commit/a35f473260084c412b8acbbdac65272612bc1d6a). This change is available from v5.0.3 that's now [available on MyGet](http://docs.servicestack.net/myget). Since you have v5.0.3 already installed you'll need to clear your NuGet packages cache, e.g.

    $ nuget locals all -clear
