### ISSUE TITLE
Getting System.NotSupportedException while trying to use PocoDynamo FromQueryIndex expression with Equals condition on a key

### ISSUE THREAD

**Issue by vikram-panigrahi** [ServiceStack/Issues#612]
**Code**

    var existingFile = dynamoDb_.FromQueryIndex<Types.FilePathIndex>(f => f.Account == account_ && f.Path.Equals(remoteFilePath)).Exec().ToList();

    public class FilePathIndex : ILocalIndex<Types.File>
    {
        public Guid Account { get; set; }
        public string S3Location { get; set; }
        [Index]
        public string Path { get; set; }
        public DateTime ModifiedUtc { get; set; }
    }

    [References(typeof(FilePathIndex))]
    [CompositeKey("Account", "S3Location")]
    public class File
    {
        public Guid Account { get; set; }
        public string S3Location { get; set; }

        public string Path { get; set; }
        public DateTime ModifiedUtc { get; set; }
    }

**Exception**

    System.NotSupportedException : Specified method is not supported.
    at ServiceStack.Aws.DynamoDb.PocoDynamoExpression.VisitColumnAccessMethod(MethodCallExpression m)
    at ServiceStack.Aws.DynamoDb.PocoDynamoExpression.VisitBinary(BinaryExpression b)
    at ServiceStack.Aws.DynamoDb.PocoDynamoExpression.VisitLambda(LambdaExpression lambda)
    at ServiceStack.Aws.DynamoDb.PocoDynamoExpression.Parse(Expression expr)
    at ServiceStack.Aws.DynamoDb.PocoDynamoExpression.Create[T](Type type, Expression`1 predicate, String paramPrefix)
    at ServiceStack.Aws.DynamoDb.QueryExpression`1.KeyCondition(Expression`1 filterExpression)
    at ServiceStack.Aws.DynamoDb.PocoDynamo.FromQueryIndex[T](Expression`1 keyExpression)
   

**Libraries**

    1. ServiceStack.Aws - v5.0.3
    2. AWSSDK.DynamoDBv2 - v3.3.7.1

**Comment by mythz** [comment]
I've added support for `Equals` method in [this commit](https://github.com/ServiceStack/ServiceStack.Aws/commit/a35f473260084c412b8acbbdac65272612bc1d6a). But please note only the extension method examples included in the docs are supported. Use the operator (e.g. `==`) when it exist.

This change is available from v5.0.3 that's now [available on MyGet](http://docs.servicestack.net/myget).
