### ISSUE TITLE
Getting System.NotSupportedException while trying to use PocoDynamo FromQueryIndex expression with Contains condition on a key

### ISSUE THREAD

**Issue by vikram-panigrahi** [ServiceStack/Issues#613]
**Code**

    var existingFile = dynamoDb_.FromQueryIndex<Types.FilePathIndex>(f => f.Account == account_ && f.Path.Contains(remoteFilePath)).Exec().ToList();

    public class FilePathIndex : ILocalIndex<Types.File>
    {
        public Guid Account { get; set; }
        public string S3Location { get; set; }
        [Index]
        public string Path { get; set; }
        public DateTime ModifiedUtc { get; set; }
    }

    [References(typeof(FilePathIndex))]
    [CompositeKey("Account", "S3Location")]
    public class File
    {
        public Guid Account { get; set; }
        public string S3Location { get; set; }

        public string Path { get; set; }
        public DateTime ModifiedUtc { get; set; }
    }

**Exception**
    
    Amazon.DynamoDBv2.AmazonDynamoDBException : Invalid operator used in KeyConditionExpression: contains
      ----> Amazon.Runtime.Internal.HttpErrorResponseException : Exception of type 'Amazon.Runtime.Internal.HttpErrorResponseException' was thrown.
       at ServiceStack.TaskExt.GetResult(Task task)
       at ServiceStack.Aws.NetCoreAwsExtensions.Query(IAmazonDynamoDB client, QueryRequest request)
       at ServiceStack.Aws.DynamoDb.PocoDynamo.Exec[T](Func`1 fn, Type[] rethrowExceptions, HashSet`1 retryOnErrorCodes)
       at ServiceStack.Aws.DynamoDb.PocoDynamo.<Query>d__102`1.MoveNext()
       at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
       at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
    --HttpErrorResponseException
       at Amazon.Runtime.HttpWebRequestMessage.<GetResponseAsync>d__20.MoveNext() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\_mobile\HttpRequestMessageFactory.cs:line 443
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Amazon.Runtime.Internal.HttpHandler`1.<InvokeAsync>d__9`1.MoveNext() in E:\JenkinsWorkspaces\v3-stage-release\AWSDotNetPublic\sdk\src\Core\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 175
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Amazon.Runtime.Internal.Unmarshaller.<InvokeAsync>d__3`1.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
       at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
       at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
       at Amazon.Runtime.Internal.ErrorHandler.<InvokeAsync>d__5`1.MoveNext()

**Libraries**

    1. ServiceStack.Aws - v5.0.3
    2. AWSSDK.DynamoDBv2 - v3.3.7.1

**Comment by mythz** [comment]
DynamoDB doesn't support `contains` in `KeyConditionExpression` as indicated in the Error message.
