### ISSUE TITLE
Grpc - No serializer defined for type  System.Nullable`1[[NodaTime.LocalDate,

### ISSUE THREAD

**Issue by ludydoo** [ServiceStack/Issues#698]
Hi there,

I am using the GrpcFeature on a ServiceStack app. 

I want to use NodaTime in my stack, from dtos to the database. I added a custom converter for postgres already, but I cannot find a way to make the serialization of my dtos work with NodaTime.

I already added the NodaTime extensions in my AppHost constructor

```
DateTimeZoneProviders.Tzdb
                .CreateDefaultSerializersForNodaTime()
                .ConfigureSerializersForNodaTime();
```

I know this is an external extension. But is this something that is somehow supported by ServiceStack? If not, what could be an alternative for getting this working? Using strings in DTOs and converting them to NodaTime.LocalDate ?

```
System.Net.Http.HttpRequestException : An error occurred while sending the request.
  ----> System.InvalidOperationException : No serializer defined for type: System.Nullable`1[[NodaTime.LocalDate, NodaTime, Version=2.4.7.0, Culture=neutral, PublicKeyToken=4226afe0d9b296d1]]
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Grpc.Net.Client.Internal.GrpcCall`2.SendAsync(HttpRequestMessage request)
   at Grpc.Net.Client.Internal.GrpcCall`2.GetResponseHeadersAsync()
   at ServiceStack.GrpcServiceClient.GetResponse[TResponse](AsyncUnaryCall`1 auc) in C:\BuildAgent\work\3481147c480f4a2f\src\ServiceStack.GrpcClient\GrpcServiceClient.cs:line 364
   at ServiceStack.GrpcServiceClient.Execute[TResponse](Object requestDto, String methodName, CancellationToken token) in C:\BuildAgent\work\3481147c480f4a2f\src\ServiceStack.GrpcClient\GrpcServiceClient.cs:line 415
   at Tec.IntegrationTests.Relationships.RelationshipTests.ShouldBeAbleToCreateRelationship() in C:\Users\lcleroux\work\tec\backend\src\Tec.IntegrationTests\Relationships\RelationshipTests.cs:line 28
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--InvalidOperationException
   at ProtoBuf.Meta.ValueMember.BuildSerializer() in C:\Code\protobuf-net\src\protobuf-net\Meta\ValueMember.cs:line 589
   at ProtoBuf.Meta.MetaType.BuildSerializer() in C:\Code\protobuf-net\src\protobuf-net\Meta\MetaType.cs:line 396
   at ProtoBuf.Meta.MetaType.get_Serializer() in C:\Code\protobuf-net\src\protobuf-net\Meta\MetaType.cs:line 383
   at ProtoBuf.Meta.RuntimeTypeModel.Serialize(Int32 key, Object value, ProtoWriter dest) in C:\Code\protobuf-net\src\protobuf-net\Meta\RuntimeTypeModel.cs:line 787
   at ProtoBuf.Meta.TypeModel.SerializeCore(ProtoWriter writer, Object value) in C:\Code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 198
   at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value, SerializationContext context) in C:\Code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 222
   at ProtoBuf.Meta.TypeModel.Serialize(Stream dest, Object value) in C:\Code\protobuf-net\src\protobuf-net\Meta\TypeModel.cs:line 208
   at ServiceStack.GrpcMarshaller`1.Serialize(T payload) in C:\BuildAgent\work\3481147c480f4a2f\src\ServiceStack.GrpcClient\GrpcServiceClient.cs:line 816
   at Grpc.Core.Marshaller`1.EmulateContextualSerializer(T message, SerializationContext context)
   at Grpc.Net.Client.StreamExtensions.WriteMessageAsync[TMessage](Stream stream, ILogger logger, TMessage message, Action`2 serializer, String grpcEncoding, Nullable`1 maximumMessageSize, Dictionary`2 compressionProviders, CallOptions callOptions)
   at Grpc.Net.Client.Internal.GrpcCall`2.<SetMessageContent>g__WriteMessageCore|66_1(Task writeMessageTask)
   at System.Net.Http.HttpContent.CopyToAsyncCore(ValueTask copyTask)
   at System.Net.Http.Http2Connection.Http2Stream.SendRequestBodyAsync(CancellationToken cancellationToken)
   at System.Net.Http.Http2Connection.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

**Comment by mythz** [comment]
Both the client and server uses the protobuf-net `RuntimeTypeModel` in `GrpcUtils.TypeModel`, any customizations would need to be configured on that on both client/server.

**Comment by mythz** [comment]
FYI since this is the public API for configuring ServiceStack's gRPC support I've decided to split out the configuration APIs into `GrpcConfig` before the next release.

So if you [clear your NuGet packages](https://docs.servicestack.net/myget#redownloading-myget-packages) the `RuntimeTypeModel` is available from `GrpcConfig.TypeModel`.
