### ISSUE TITLE
ArgumentException : Cannot bind to the target method because its signature is not compatible with that of the delegate type.

### ISSUE THREAD

**Issue by malibVB** [ServiceStack/Issues#702]
Dear Support,

following exception occurs when auto mapping a model with viewmodel with same methods but different parameters ! 

```csharp
System.ArgumentException
  HResult=0x80070057
  Message=Cannot bind to the target method because its signature is not compatible with that of the delegate type.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.RuntimeMethodInfo.CreateDelegateInternal(Type delegateType, Object firstArgument, DelegateBindingFlags bindingFlags)
   at System.Reflection.RuntimeMethodInfo.CreateDelegate(Type delegateType)
   at ServiceStack.AssignmentMember.CreateGetter() in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\AutoMappingUtils.cs:line 1085
   at ServiceStack.AssignmentEntry..ctor(String name, AssignmentMember from, AssignmentMember to) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\AutoMappingUtils.cs:line 1048
   at ServiceStack.AssignmentDefinition.AddMatch(String name, AssignmentMember readMember, AssignmentMember writeMember) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\AutoMappingUtils.cs:line 1140
   at ServiceStack.AutoMappingUtils.<>c__DisplayClass27_0.<GetAssignmentDefinition>b__0(String <p0>) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\AutoMappingUtils.cs:line 457
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at ServiceStack.AutoMappingUtils.GetAssignmentDefinition(Type toType, Type fromType) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\AutoMappingUtils.cs:line 445
   at ServiceStack.AutoMappingUtils.PopulateFromPropertiesWithoutAttribute[To,From](To to, From from, Type attributeType) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\AutoMappingUtils.cs:line 598
   at UnitTests.AutoMapperTest.Test_PopulateFromPropertiesWithoutAttribute() in K:\Library II\4. VB\09 Tests\UnitTests\AutoMapperTest.cs:line 37
```

This is the test code I have created:

```csharp
   [TestClass]
   public class AutoMapperTest
   {
      [TestMethod]
      public void Test_PopulateFromPropertiesWithoutAttribute  ()
      {
         MyModel     myModel     = new MyModel ();
         MyViewModel myViewModel = new MyViewModel ();
         myViewModel.MyProp = "Test";
         myModel.PopulateFromPropertiesWithoutAttribute (myViewModel, typeof(IgnoreOnPopulateAttribute));
         Assert.AreEqual (myModel.MyProp, myViewModel.MyProp);
      }

      class MyModel
      {
         public void MyMethode (string myProp)
         {
            MyProp = myProp;
         }

         public string MyProp { get; set; }
      }

      class MyViewModel
      {
         public void MyMethode ()
         {
            MyProp = "MyMethode";
         }

         public string MyProp { get; set; }
      }
   }
```

Please see also the attached gif for more information.

![AutoMapperArgumentException](https://user-images.githubusercontent.com/6638897/72355171-39020380-36e7-11ea-9fee-d53a1e9f6c57.gif)

Could you verify and fix it please.

**Comment by mythz** [comment]
Are you using the latest ServiceStack v5.8? As I'm not able to repro this, I've added a test for this in [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/03bb422a091f05fec37c1bffd796687b10a421e1) but it passes without Exception.

**Comment by malibVB** [comment]
Yes, I'm using the latest version of ServiceStack v5.8.
Updated today.

I verfied your example !

in your code the method "MyMethod" of the class "TestMethode2" must have the parameter !

```
      public class TestMethod2
      {
         public void MyMethod(string myProp)
         {
            MyProp = nameof(MyMethod);
         }
         public string MyProp { get; set; }
      }
```

Then you get also the exception.

Thanx for your reply

**Comment by mythz** [comment]
I don't understand, your `TestMethod2` is exactly the same as mine, one has a parameter the other doesn't, I've even tried swapping it so TestMethod has the parameter, the test still passes.

Can you rewrite this test so it repros the issue:

```csharp
public class TestMethod
{
    public void MyMethod(string myProp)
    {
        MyProp = myProp;
    }
    public string MyProp { get; set; }
}

public class TestMethod2
{
    public void MyMethod()
    {
        MyProp = nameof(MyMethod);
    }
    public string MyProp { get; set; }
}

[Test]
public void Does_not_try_to_map_methods()
{
    var from = new TestMethod();
    var to = new TestMethod2();
    from.MyProp = "Test";
    to.PopulateFromPropertiesWithoutAttribute(from, typeof(IgnoreDataMemberAttribute));
    Assert.That(from.MyProp, Is.EqualTo(to.MyProp));
}
```

**Comment by malibVB** [comment]
No, the code is not the same.

Change/swap the methods of the classes `TestMethod` and `TestMethod2`.

See commented code below.

```csharp
public class TestMethod
{
    // Change this
    // public void MyMethod(string myProp)
    public void MyMethod()
    {
        MyProp = myProp;
    }
    public string MyProp { get; set; }
}

public class TestMethod2
{
    // Change this
    // public void MyMethod()
    public void MyMethod(string myProp)
    {
        MyProp = nameof(MyMethod);
    }
    public string MyProp { get; set; }
}

[Test]
public void Does_not_try_to_map_methods()
{
    var from = new TestMethod();
    var to = new TestMethod2();
    from.MyProp = "Test";
    to.PopulateFromPropertiesWithoutAttribute(from, typeof(IgnoreDataMemberAttribute));
    Assert.That(from.MyProp, Is.EqualTo(to.MyProp));
}
```

Why does the auto mapper try to map methods ?
It doesn't make sense to me.

**Comment by mythz** [comment]
AutoMapping is able to map calculated methods that matches the shape of object getter/setter delegates. I just needed a repro to identify the issue, which should now be resolved from [this commit](https://github.com/ServiceStack/ServiceStack.Text/commit/f70f16fbd5ccb94cdd36b0da78c59226da0bc379).

This change is available from v5.8.1 that's now [available on MyGet](https://docs.servicestack.net/myget).

**Comment by malibVB** [comment]
OK, it's working, thank you for the quick bugfix !

But I don't understand why the mapper try's to map methods !
Could you provide me an example implementation for that purpose ?

**Comment by mythz** [comment]
IIRC it was the original implementation for implementing getters/setters, but just tested that it's needed anymore so I've [just removed it](https://github.com/ServiceStack/ServiceStack.Text/commit/172afd4a5a41decb93b29dfd53425bcf4c2f8a58).
