### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by mosherjelly** [ServiceStack/Issues#733]
I have purchased an "Indie Developer" license, but seems that i'm getting quota errors: 

"ServiceStack.LicenseException: The free-quota limit on '6000 Redis requests per hour' has been reached. Please see https://servicestack.net to upgrade to a commercial license or visit https://github.com/ServiceStackV3/ServiceStackV3 to revert back to the free ServiceStack v3.
   at ServiceStack.LicenseUtils.ApprovedUsage(LicenseFeature licenseFeature, LicenseFeature requestedFeature, Int32 allowedUsage, Int32 actualUsage, String message) in C:\BuildAgent\work\912418dcce86a188\src\ServiceStack.Text\LicenseUtils.cs:line 299
   at ServiceStack.Redis.RedisNativeClient.WriteCommandToSendBuffer(Byte[][] cmdWithBinaryArgs) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 400
   at ServiceStack.Redis.RedisNativeClient.SendReceive[T](Byte[][] cmdWithBinaryArgs, Func`1 fn, Action`1 completePipelineFn, Boolean sendWithoutRead) in C:\BuildAgent\work\b2a0bfe2b1c9a118\src\ServiceStack.Redis\RedisNativeClient_Utils.cs:line 598
   at Playtika.PSF.MergeBattleCommon.Pipeline.Middleware.LiveData.HttpLayerLoggerMiddleware.PublishMessage(String topic, Object message)
   at Playtika.PSF.MergeBattleCommon.Pipeline.Middleware.LiveData.HttpLayerLoggerMiddleware.PublishResponse(String playerId, String url, String responseContent, String statusCode)"

**Comment by mythz** [comment]
This suggests the license isn't property registered where it's being used, the registration options are listed at:
https://servicestack.net/download#register

Please confirm the Application throwing this Exception has a properly configured license, if it is please email team@servicestack.net with your License Key and code/config you're using so we can verify if it's valid & being properly registered.
