### ISSUE TITLE
Dart JsonWebClient - StatusCode  is null

### ISSUE THREAD

**Issue by sbosell** [ServiceStack/Issues#740]
The following code generates a `TypeError: Cannot read property 'statusCode' of null` when using the JsonWebClient in flutter/dart targeted at web.  The JsonServiceClient doesn't have an issue when targeting android which leads me to believe it is a bug in the JsonWebClient.

The sample code below is super simple.  Instantiate a client depending on the environment and call a simple autoquery endpoint.  You can ignore the per environment piece and just test against JsonWebClient.

```
class ApiClient {
  static IServiceClient getClient(String url) {
    if (kIsWeb) {
      return JsonWebClient(url);
    } else {
      return JsonServiceClient(url);
    }
  }
}

class _TestPendingScreenState extends State<TestPendingScreen> {
  TestRequestDatasource crd = TestRequestDatasource();
  IServiceClient client =
      ApiClient.getClient("https://my-service-url.com/");

  TestAutoQuery apiRequest = TestAutoQuery();
  @override
  void initState() {
    super.initState();
    client.get(apiRequest).then((data) {
      crd.setDataSource(data.results);
    });
  }

```

TypeError: Cannot read property 'statusCode' of null
    at web_client.JsonWebClient.new.sendRequest (http://localhost:55669/packages/servicestack/web_client.dart.lib.js:458:21)
    at sendRequest.throw (<anonymous>)
    at http://localhost:55669/dart_sdk.js:37609:38
    at _RootZone.runBinary (http://localhost:55669/dart_sdk.js:37462:58)
    at _FutureListener.thenAwait.handleError (http://localhost:55669/dart_sdk.js:32453:48)
    at handleError (http://localhost:55669/dart_sdk.js:33004:51)
    at Function._propagateToListeners (http://localhost:55669/dart_sdk.js:33030:17)
    at _Future.new.[_completeError] (http://localhost:55669/dart_sdk.js:32877:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:55669/dart_sdk.js:32915:31)
    at Object._microtaskLoop (http://localhost:55669/dart_sdk.js:37718:13)
    at _startMicrotaskLoop (http://localhost:55669/dart_sdk.js:37724:13)

**Comment by sbosell** [comment]
This can be closed, it is a CORS issue.
