### ISSUE TITLE
Cannot install ServiceStack VS extension on ARM

### ISSUE THREAD

**Issue by edumicse** [ServiceStack/Issues#792]
Running virtual Windows 11 on Mac 2 throws an exception and it cannot be installed.

Log data:
2023-05-30 13:50:03 - Initializing Install...
2023-05-30 13:50:03 - Searching for applicable products...
2023-05-30 13:50:04 - Found installed product - Visual Studio Professional 2022
2023-05-30 13:50:04 - Found installed product - Visual Studio Professional 2017
2023-05-30 13:50:04 - Found installed product - Visual Studio Enterprise 2019
2023-05-30 13:50:04 - Found installed product - Global Location
2023-05-30 13:50:04 - Extension Details...
2023-05-30 13:50:04 - 	Identifier         : 97413fa1-bad9-4cfb-a91c-c8d7b2c3c844
2023-05-30 13:50:04 - 	Name               : ServiceStackVS
2023-05-30 13:50:04 - 	Author             : ServiceStack
2023-05-30 13:50:04 - 	Version            : 3.1.0
2023-05-30 13:50:04 - 	Description        : Tools for use with the ServiceStack framework.
2023-05-30 13:50:04 - 	Locale             : en-US
2023-05-30 13:50:04 - 	MoreInfoURL        : https://github.com/ServiceStack/ServiceStackVS
2023-05-30 13:50:04 - 	InstalledByMSI     : False
2023-05-30 13:50:04 - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
2023-05-30 13:50:04 - 	SignatureState     : Unsigned
2023-05-30 13:50:04 - 	Supported Products : 
2023-05-30 13:50:04 - 		Microsoft.VisualStudio.Community
2023-05-30 13:50:04 - 			Version : [17.0,18.0)
2023-05-30 13:50:04 - 			ProductArchitecture : amd64
2023-05-30 13:50:04 - 		Microsoft.VisualStudio.Pro
2023-05-30 13:50:04 - 			Version : [17.0,18.0)
2023-05-30 13:50:04 - 			ProductArchitecture : amd64
2023-05-30 13:50:04 - 		Microsoft.VisualStudio.Enterprise
2023-05-30 13:50:04 - 			Version : [17.0,18.0)
2023-05-30 13:50:04 - 			ProductArchitecture : amd64
2023-05-30 13:50:04 - 	References         : 
2023-05-30 13:50:04 - 	Prerequisites      : 
2023-05-30 13:50:04 - 		-------------------------------------------------------
2023-05-30 13:50:04 - 		Identifier   : Microsoft.Net.Component.4.7.2.TargetingPack
2023-05-30 13:50:04 - 		Name         : .NET Framework 4.7.2 targeting pack
2023-05-30 13:50:04 - 		Version      : [17.0,18.0)
2023-05-30 13:50:04 - Signature Details...
2023-05-30 13:50:04 - 	Extension is not signed.
2023-05-30 13:50:04 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by mythz** [comment]
ServiceStackVS for ARM is not supported. You can the [x dotnet tool](https://docs.servicestack.net/add-servicestack-reference#simple-command-line-utilities) to generate and update Add ServiceStack References which you should be able to [Integrate with Visual Studio as an external tool](https://docs.servicestack.net/add-servicestack-reference#integrate-with-visual-studio).
